
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
  var current_user_id =  localStorage.getItem("ls_uid") ;
var current_user_name =  localStorage.getItem("ls_uname") ; 
  var app_phone_id =  localStorage.getItem("app_phone_id") ;
 var physical_stock_array = [];
$(document).ready(function(){
 
console.log(app_phone_id);


  $("#menu_bar").load('menu.html',
    function() { 
      var lo = (window.location.pathname.split("/").pop());
      var web_addr = "#"+ (lo.substring(0, lo.indexOf(".")))
 
    
     if($(web_addr).find("a").hasClass('nav-link'))
     {
      $(web_addr).find("a").toggleClass('active')
     }
     else if($(web_addr).find("a").hasClass('dropdown-item'))
{
$(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
}
      
     
    }
 );



    // check_login();
    
  $("#unamed").text(localStorage.getItem("ls_uname"))


$("#phone_code").text("app phone id: " + app_phone_id)

$("#sec_stock").on("click", function(event) {
  event.preventDefault();
  // TODO: handle click here

window.open("marketing_lead.html?phone_id="+app_phone_id, '_blank');
});

$("#camera_btn").on("click", function(event) {
  event.preventDefault();
  // TODO: handle click here
  captureWithDbData();
});



});

function captureWithDbData() {
var dbParams = JSON.stringify({ "godown_id": 1166 });
var url = "https://jaysan.cloud/php/upload_dc.php";

    if (window.AndroidBridge) {
        // Kotlin will take the photo, compress it, 
        // and include these params in the POST request to app_upload.php
        AndroidBridge.takePhoto(dbParams, url);
    }
}

// Global callbacks called by the Android app
window.onUploadSuccess = function (response) {
    console.log("Upload Success:", response);
    alert("Photo uploaded successfully!");
};

window.onUploadError = function (error) {
    console.error("Upload Error:", error);
    alert("Upload failed. Error code: " + error);
};



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });










  

   



function check_login()
{
 
if (localStorage.getItem("logemail") == null && phone_id == null )  {
 window.location.replace("login.html");
}
else if (localStorage.getItem("logemail") == null && phone_id != null )
 {
get_current_userid_byphoneid();
$('#menu_bar').hide()
 }

 else
 {
   
 }
}


function get_current_userid_byphoneid()
   {
     $.ajax({
       url: "php/get_current_employee_id_byphoneid.php",
       type: "get", //send it through get method
       data: {
         phone_id:phone_id,
        
      
      },
       success: function (response) {
      
      
      if (response.trim() != "error") {
       var obj = JSON.parse(response);
      

      console.log(response);
      
      
       obj.forEach(function (obj) {
         current_user_id = obj.emp_id;
         current_user_name =  obj.emp_name;
       });
      
    //    get_sales_order()
      }
      
      else {
       salert("Error", "User ", "error");
      }
      
      
         
       },
       error: function (xhr) {
           //Do Something to handle error
       }
      });
   }

  
   function shw_toast(title,des,theme)
   {
   
     
         $('.toast-title').text(title);
         $('.toast-description').text(des);
   var toast = new bootstrap.Toast($('#myToast'));
   toast.show();
   }  

   function get_millis(t)
   {
    
    var dt = new Date(t);
    return dt.getTime();
   }



   function get_cur_millis()
   {
    var dt = new Date();
    return dt.getTime();
   }


   function get_today_date(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();
  
console.log(mins)

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T"+ hour + ":"+ mins; 
    return today;
   }

   function get_today_start_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T00:00"; 

    return get_millis(today)
     
   }


   function get_today_end_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T23:59"; 

    return get_millis(today)
     
   }

   function salert(title, text, icon) {
  

    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date( millis)
{
  var d = new Date(millis); // Parameter should be long value

  
return d.toLocaleString('en-GB');

}