
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
var current_user_id = localStorage.getItem("ls_uid");
var current_user_name = localStorage.getItem("ls_uname");
var physical_stock_array = [];
var sts = "created"
var cn_emp = "all"
$(document).ready(function () {



  $("#menu_bar").load('menu.html',
    function () {
      var lo = (window.location.pathname.split("/").pop());
      var web_addr = "#" + (lo.substring(0, lo.indexOf(".")))


      if ($(web_addr).find("a").hasClass('nav-link')) {
        $(web_addr).find("a").toggleClass('active')
      }
      else if ($(web_addr).find("a").hasClass('dropdown-item')) {
        $(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
      }


    }
  );



  check_login();

  $("#unamed").text(localStorage.getItem("ls_uname"))
  get_credit_note_report()

  get_credit_note_sts()

  $('#sel_usr_in').change(function () {
    cn_emp = $(this).val()
    get_credit_note_report()
  });

  $('#sel_cn_sts').change(function () {
    sts = $(this).val()
    get_credit_note_report()
  });


  $("#credit_note_report").on("click", "tr td button", function (event) {
    event.preventDefault();
    var cn = $(this).closest("tr").find("td").eq(5).html()
    // your logic here
    var dcf_id = $(this).val()
    if ($(this).hasClass("accept")) {
      swal({
        title: "Are you sure - accept? ",
        text: "You will not be recover this  again!",
        icon: "success",
        buttons: [
          'No, cancel it!',
          'Yes, I am sure!'
        ],
        dangerMode: true,
      }).then(function (isConfirm) {
        if (isConfirm) {
          swal({
            title: 'Applied!',
            text: 'successfully Deleted!',
            icon: 'success'
          }).then(function () {

            update_dcf_credit_note(dcf_id, "accepted", cn) // <--- submit form programmatically


          });
        } else {
          swal("Cancelled", "This is safe :)", "error");
        }
      })
    }

    else {
      update_dcf_credit_note(dcf_id, "created", cn)
    }
  });


});



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });




function update_dcf_credit_note(dcf_id, sts, cn) {




  $.ajax({
    url: "php/update_dcf_credit_note.php",
    type: "get", //send it through get method
    data: {
      dcf_id: dcf_id,
      cn_sts: sts,
      credit_note_no: cn


    },
    success: function (response) {

      console.log(response);

      if (response.trim() == "ok") {

        shw_toast("Success", " Updated", "success")
        get_credit_note_report()

      }





    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });




}


function get_employee() {


  $.ajax({
    url: "php/get_all_emp_hi.php",
    type: "get", //send it through get method
    data: {
      emp_id: current_user_id

    },
    success: function (response) {


      if (response.trim() != "error") {

        var obj = JSON.parse(response);



        obj.forEach(function (obj) {


          $("#sel_usr_in").append(" <option value='" + obj.emp_id + "'>" + obj.emp_name + "</option>");



        });


      }

      else {
        salert("Error", "User ", "error");
      }



    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });




}


function get_credit_note_report() {


  $.ajax({
    url: "php/get_credit_note_report.php",
    type: "get", //send it through get method
    data: {
      emp_id: cn_emp,
      sts: sts
    },
    success: function (response) {

      $('#credit_note_report').empty()

      if (response.trim() != "error") {
        console.log(response);

        if (response.trim() != "0 result") {

          var obj = JSON.parse(response);
          var count = 0


          obj.forEach(function (obj) {
            count = count + 1;
            $('#credit_note_report').append("<tr> <td>" + count + "</td> <td>" + obj.cus_name + "</td> <td>" + obj.cus_phone + "</td> <td>" + obj.invoice_no + "</td> <td>" + obj.cn_amount + "</td> <td contenteditable=\"true\">" + obj.credit_note_no + "</td> <td>" + obj.credit_note_date + "</td> <td>" + obj.cn_sts + "</td> <td>" + obj.emp_name + "</td> <td class='d-flex  gap-2'> <button type='submit' value='" + obj.dcf_id + "' class='btn btn-primary btn-sm small Add d-none' id=''>Add</button> <button type='submit' value='" + obj.dcf_id + "' class='btn btn-success btn-sm small accept' id=''>accept</button></td> </tr>")
          });


        }
        else {
          $("#credit_note_report").append("<tr><td colspan='10' scope='col'>No Data</td></tr>");

        }
      }





    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });




}

function get_credit_note_sts() {


  $.ajax({
    url: "php/get_credit_note_sts.php",
    type: "get", //send it through get method
    data: {

    },
    success: function (response) {



      if (response.trim() != "error") {
        console.log(response);

        if (response.trim() != "0 result") {

          var obj = JSON.parse(response);
          var count = 0


          obj.forEach(function (obj) {
            count = count + 1;
            if (obj.cn_sts != "" && obj.cn_sts != "verified") {

              $("#sel_cn_sts").append(` <option value='${obj.cn_sts}' >${obj.cn_sts}</option>`);
            }



          });


        }
        else {
          // $("#@id@") .append("<td colspan='0' scope='col'>No Data</td>");

        }
      }





    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });




}







function check_login() {

  if (localStorage.getItem("logemail") == null && phone_id == null) {
    window.location.replace("login.html");
  }
  else if (localStorage.getItem("logemail") == null && phone_id != null) {
    get_current_userid_byphoneid();
    $('#menu_bar').hide()
  }

  else {
    get_employee()
  }
}


function get_current_userid_byphoneid() {
  $.ajax({
    url: "php/get_current_employee_id_byphoneid.php",
    type: "get", //send it through get method
    data: {
      phone_id: phone_id,


    },
    success: function (response) {


      if (response.trim() != "error") {
        var obj = JSON.parse(response);


        console.log(response);


        obj.forEach(function (obj) {
          current_user_id = obj.emp_id;
          current_user_name = obj.emp_name;
        });

        get_employee()
      }

      else {
        salert("Error", "User ", "error");
      }



    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });
}


function shw_toast(title, des, theme) {


  $('.toast-title').text(title);
  $('.toast-description').text(des);
  var toast = new bootstrap.Toast($('#myToast'));
  toast.show();
}

function get_millis(t) {

  var dt = new Date(t);
  return dt.getTime();
}



function get_cur_millis() {
  var dt = new Date();
  return dt.getTime();
}


function get_today_date() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  var hour = date.getHours();
  var mins = date.getMinutes();

  console.log(mins)

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T" + hour + ":" + mins;
  return today;
}

function get_today_start_millis() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T00:00";

  return get_millis(today)

}


function get_today_end_millis() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T23:59";

  return get_millis(today)

}

function salert(title, text, icon) {


  swal({
    title: title,
    text: text,
    icon: icon,
  });
}



function millis_to_date(millis) {
  var d = new Date(millis); // Parameter should be long value


  return d.toLocaleString('en-GB');

}