
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
var current_user_id = localStorage.getItem("ls_uid");
var current_user_name = localStorage.getItem("ls_uname");
var physical_stock_array = [];
var obj = [];
$(document).ready(function () {


    $("#menu_bar").load('menu.html',
        function () {
            var lo = (window.location.pathname.split("/").pop());
            var web_addr = "#" + (lo.substring(0, lo.indexOf(".")))


            if ($(web_addr).find("a").hasClass('nav-link')) {
                $(web_addr).find("a").toggleClass('active')
            }
            else if ($(web_addr).find("a").hasClass('dropdown-item')) {
                $(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
            }


        }
    );



    $("#po_report_search_a").on("keyup", function () {
        const value = $(this).val().toLowerCase();

        $("#po_dashboard_details tr").each(function () {
            const rowText = $(this).text().toLowerCase();
            $(this).toggle(rowText.indexOf(value) !== -1);
        });
    });


    check_login();

    $("#unamed").text(localStorage.getItem("ls_uname"))

    get_jaysan_po_material()
    $("#printInvoice").on("click", function (event) {
        event.preventDefault();
        // TODO: handle click here

        const win = window.open("storage%2Fpdf%2Finvoice1001.pdf", "_blank");
        // Some browsers need a delay before printing
        const printTimer = setInterval(() => {
            if (win.document.readyState === "complete") {
                clearInterval(printTimer);
                win.focus();
                win.print();
            }
        }, 500);
    });


    $("#print").on("click", function (event) {
        event.preventDefault();
        // TODO: handle click here
        var invoiceHtml = $("#invoicePreview").prop("outerHTML");

        // Encode it to protect HTML structure in POST
        var encodedHtml = encodeURIComponent(invoiceHtml);
        $.ajax({
            url: "pdf_handler.php",
            method: "POST",
            data: {
                save_path: "storage/pdf/invoice1001",
                file_name: "Invoice.pdf",
                unique_file: "no",
                header_html: "<h3 class='text-center' style='text-align: center;'>PURCHASE ORDER</h3>",
                footer_html: "<p>Generated by HS Tech Soft ERP</p>",
                body_html: encodedHtml,
                orientation: "portrait",
                paper_size: "A4",
                stream: "no",
                // email_to: "nklharish1@gmail.com",
                // email_subject: "Invoice #1001",
                // email_body: "Hello, please find attached your invoice.",
                // pdf_password: "",        // optional
                // watermark_text: ""       // optional
            },
            success: function (res) {
                console.log(res);
                if (res.download_url) {
                    // 3️⃣ open PDF and trigger browser print dialog
                    const win = window.open(res.download_url, "_blank");
                    // Some browsers need a delay before printing
                    const printTimer = setInterval(() => {
                        if (win.document.readyState === "complete") {
                            clearInterval(printTimer);
                            win.focus();
                            win.print();
                        }
                    }, 500);
                } else {
                    alert("PDF generated, but no download URL returned");
                }
            },
            error: function (xhr) {
                alert("Error: " + xhr.responseText);
            }
        });
    });


    $("#myInput_web").on("keyup", function () {
        var value = $(this).val().toLowerCase();

        $("#material_chart tr").filter(function () {
            var materialName = $(this).find("td:nth-child(2)").text().toLowerCase();
            $(this).toggle(materialName.indexOf(value) > -1);
        });
    });



    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(get_material_chart);

    // Fetch data from your PHP API
    function get_material_chart() {
        $.ajax({
            url: "php/get_material_chart.php",
            type: "GET",
            success: function (response) {
                if (response.trim() !== "error") {
                    var obj = JSON.parse(response);
                    drawChart(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChart(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Part Name', 'Total Required Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.part_name, parseInt(item.total_req_qty)]);
            $("#material_chart").append("<tr data-part_id=" + item.part_id + "><td>" + count + "</td><td>" + item.part_name + "</td><td>" + item.total_req_qty + "</td><td>" + item.frq + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Material Chart',
            is3D: true,
            // pieSliceText: 'value',
            // chartArea: { width: '65%', height: '80%' }
        };

        var chart = new google.visualization.PieChart(document.getElementById('material_piechart_3d'));
        chart.draw(data, options);
    }
    $("#material_chart").on("click", "tr", function () {
        $("#next_chart").removeClass("d-none");
        $("#part_name_head").text($(this).find("td").eq(1).text() + "  Chart")
        get_mf_company_chart($(this).data("part_id"));
        get_material_frequency_chart($(this).data("part_id"));
        // Fetch data from your PHP API

    })
    function get_mf_company_chart(part_id) {
        $.ajax({
            url: "php/get_mf_company_chart.php",
            type: "GET",
            data: {
                part_id: part_id,
            },
            success: function (response) {
                console.log(response);

                if (response.trim() !== "error") {
                    $("#company_chart").empty();
                    var obj = JSON.parse(response);
                    drawChartcompany(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChartcompany(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Company Name', 'Total Required Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.creditor_name, parseInt(item.total_req_qty)]);
            $("#company_chart").append("<tr data-part_id=" + item.part_id + "><td>" + count + "</td><td>" + item.creditor_name + "</td><td>" + item.total_req_qty + "</td><td>" + item.freq + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Company Chart',
            is3D: true,
            // pieSliceText: 'value',
            // chartArea: { width: '85%', height: '80%' }
        };

        var chart = new google.visualization.PieChart(document.getElementById('company_piechart_3d'));
        chart.draw(data, options);
    }

    function get_material_frequency_chart(part_id) {
        $.ajax({
            url: "php/get_material_frequency_chart.php",
            type: "GET",
            data: {
                part_id: part_id,
            },
            success: function (response) {
                console.log(response);

                if (response.trim() !== "error") {
                    $("#frequency_chart").empty();
                    var obj = JSON.parse(response);
                    drawChartfrequency(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChartfrequency(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Date', 'Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.for_date, parseInt(item.total_req_qty)]);
            $("#frequency_chart").append("<tr><td>" + count + "</td><td>" + item.for_date + "</td><td>" + item.total_req_qty + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Frequency Chart',
            is3D: true,
            curveType: 'function',
            // pieSliceText: 'value',
            // chartArea: { width: '85%', height: '80%' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('frequency_line_chart'));
        chart.draw(data, options);
    }


    google.charts.setOnLoadCallback(get_mrf_chart);

    function get_mrf_chart() {
        $.ajax({
            url: "php/mrf_graph.php",
            type: "GET",
            success: function (response) {
                if (response.trim() !== "error") {
                    var obj = JSON.parse(response);
                    drawMRFChart(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    function drawMRFChart(dataArray) {

        // Count statuses
        let statusCount = {};

        dataArray.forEach(item => {
            let status = item.status;
            statusCount[status] = (statusCount[status] || 0) + 1;
        });

        // Prepare chart data
        let chartData = [['Status', 'Count']];
        let mdCount = 0; // FIXED accumulator

        for (let key in statusCount) {
            chartData.push([key, statusCount[key]]);

            if (key == 'created') {
                $("#request").text(statusCount[key]);
                // $("#request").css("color", "#ff9900");
            }
            else if (key == 'tally_stock_approved') {
                $("#tally").text(statusCount[key]);
                $("#tally").css("color", "#ff9900");
            }
            else if (key == 'approved' || key == 'md_redo') {

                mdCount += statusCount[key];
                $("#purchase").text(mdCount);
                $("#purchase").css("color", "#3366cc");
            }
            else if (key == 'md_approved') {
                $("#md").text(statusCount[key]);
                $("#md").css("color", "#dc3912");
            }
            else if (key == 'order_placed') {
                $("#order").text(statusCount[key]);
                // $("#order").css("color", ""); // add if needed
            }
        }


        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'MRF Status Chart',
            is3D: true,
            pieSliceText: 'value',
            legend: { position: 'right' },
            chartArea: { width: '100%', height: '100%' },
            // colors: ['#0d6efd', '#6f42c1', '#d63384', '#198754', '#fd7e14'] // CUSTOM COLORS
        };

        var chart = new google.visualization.PieChart(
            document.getElementById("MRF_chart")
        );
        chart.draw(data, options);
    }


    $('#company').on('input', function () {
        //check the value not empty

        if ($('#company').val() != "") {
            $('#company').autocomplete({
                //get data from databse return as array of object which contain label,value

                source: function (request, response) {

                    console.log(response);
                    $.ajax({
                        url: "php/get_po_report_search_auto.php",
                        type: "get", //send it through get method
                        data: {
                            part: request.term,
                            term: ""
                        },
                        dataType: "json",
                        success: function (data) {

                            console.log("data : " + data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.creditor_name,
                                    value: item.creditor_name,
                                    id: item.po_order_to,

                                };
                            }));

                        }

                    });
                },
                minLength: 2,
                cacheLength: 0,
                select: function (event, ui) {

                    $(this).data("po_order_to", ui.item.id);



                },

            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div><strong>" + item.label + "</strong> </div>")
                    .appendTo(ul);
            };
        }

    });

    $('#part').on('input', function () {

        // check the values not empty
        if ($('#part').val() !== "") {

            $('#part').autocomplete({
                source: function (request, response) {
                    console.log(response);

                    $.ajax({
                        url: "php/get_part_name_auto_wel.php",
                        type: "get",
                        dataType: "json",
                        data: {
                            term: "name",
                            part: request.term,
                            godwon_id: '',
                            department_id: '',
                            section_id: '',
                        },
                        success: function (data) {
                            console.log(data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.part_name,
                                    value: item.part_name,
                                    id: item.part_id
                                };
                            }));
                        },
                        error: function (xhr, status, error) {
                            console.error("Autocomplete error:", error);
                        }
                    });
                },
                select: function (event, ui) {
                    // When a user selects a suggestion
                    $(this).data("part_id", ui.item.id);
                    console.log("part_id :", ui.item);
                }
            })
                // ✅ Custom rendering of autocomplete dropdown
                .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                        .append("<div><strong>" + item.label + "</strong></div>")
                        .appendTo(ul);
                };
        }
    });


    $('#emp_name').on('input', function () {
        if ($('#emp_name').val() != "") {
            $('#emp_name').autocomplete({
                //get data from databse return as array of object which contain label,value

                source: function (request, response) {

                    console.log(response);
                    $.ajax({
                        url: "php/get_emp_auto.php",
                        type: "get", //send it through get method
                        data: {
                            emp_name: request.term,
                        },
                        dataType: "json",
                        success: function (data) {

                            console.log("data : " + data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.emp_name,
                                    value: item.emp_name,
                                    id: item.emp_id,

                                };
                            }));

                        }

                    });
                },
                minLength: 2,
                cacheLength: 0,
                select: function (event, ui) {

                    $(this).data("emp_id", ui.item.id);



                },

            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div><strong>" + item.label + "</strong> </div>")
                    .appendTo(ul);
            };
        }

    });

    $('#raw_material').on('input', function () {

        // check the values not empty
        if ($('#raw_material').val() !== "") {

            $('#raw_material').autocomplete({
                source: function (request, response) {
                    console.log(response);

                    $.ajax({
                        url: "php/get_po_report_search_auto.php",
                        type: "get",
                        dataType: "json",
                        data: {
                            part: request.term,
                            term: "raw"
                        },
                        success: function (data) {
                            console.log(data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.part_name,
                                    value: item.part_name,
                                    id: item.po_material_id
                                };
                            }));
                        },
                        error: function (xhr, status, error) {
                            console.error("Autocomplete error:", error);
                        }
                    });
                },
                select: function (event, ui) {
                    // When a user selects a suggestion
                    $(this).data("po_material_id", ui.item.id);
                    console.log("po_material_id :", ui.item);
                }
            })
                // ✅ Custom rendering of autocomplete dropdown
                .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                        .append("<div><strong>" + item.label + "</strong></div>")
                        .appendTo(ul);
                };
        }
    });

    $("#search").on("click", function () {
        var part = $("#part").data("part_id");
        var company = $("#company").data("po_order_to");
        var raw_material = $("#raw_material").data("po_material_id");
        var emp_id = $("#emp_name").data("emp_id");
        var fdate = $("#from_date").val();
        var tdate = $('#to_date').val();

        get_po_dashboard(part, emp_id, raw_material, fdate, tdate, company)
    })


    $("#flexSwitchCheckDefault").on("change", function () {

        if ($(this).is(":checked")) {
            $(".material_chart_data").addClass("d-none");
            $(".mrf_table").removeClass("d-none");
        }
        else {
            $(".material_chart_data").removeClass("d-none");
            $(".mrf_table").addClass("d-none");
        }

    })

    $("#excel_btn").on("click", function () {

        if (!obj.length) {
            salert("Warning", "No data to export", "warning");
            return;
        }

        const excelData = [[
            "S.No",
            "MRF Form.No",
            "Form Raised Date",
            "Part Name",
            "Form Raised Person Name",
            "Requested Qty",
            "Purchase Part Name",
            "Purchase Qty",
            "DC Person Name",
            "PO.No",
            "Supplier Name",
            "PO Batch Date",
            "Status",
            "Material Status",
            "Received By",
            "Received Qty",
            "Received Date"
        ]];

        obj.forEach((row, index) => {

            var rd = '';
            var rdq = '';
            var rddate = '';

            row.rd == "No Material Received" ? [] : JSON.parse(row.rd).forEach(function (r) {
                rd = r.received_by
                rdq = r.grn_receive_qty
                rddate = r.grn_dc_date
            })

            var po_no = '';

            row.batch == "no purchase entry" ? [] : JSON.parse(row.batch).forEach(function (b) {
                po_no = b.po_no
            })


            excelData.push([
                index + 1,
                row.mrf_id,
                row.dated,
                row.part_name,
                row.purchase_req_by,
                row.req_qty + " " + row.mrf_uom,
                row.raw_material_name,
                row.order_qty + " " + row.uom,
                row.purchase_req_by,
                po_no,
                row.supplier_name || '',
                row.batch_date,
                row.status,
                row.rd == "No Material Received" ? "Not Received" : "Received",
                row.rd == "No Material Received" ? "No One Received" : rd,
                row.rd == "No Material Received" ? "No Qty Received" : rdq,
                row.rd == "No Material Received" ? "Not Received" : rddate
            ]);
        });

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.aoa_to_sheet(excelData);

        XLSX.utils.book_append_sheet(wb, ws, "PO Dashboard");

        XLSX.writeFile(wb, "PO_Dashboard.xlsx");
    });


    $("#excel_view_btn").on("change", function () {
        if ($(this).is(":checked")) {
            $("#excel_type_po").removeClass("d-none");
            $("#card_type_po").addClass("d-none");
        }
        else {
            $("#card_type_po").removeClass("d-none");
            $("#excel_type_po").addClass("d-none");
        }
    })

    $("#excel_download_btn").click(function () {

        let table = document.querySelector("#excel_type_po table");

        if (!table) {
            salert("Warning", "No data available to export", "warning");
            return;
        }

        let workbook = XLSX.utils.table_to_book(table, { sheet: "MRF Report" });

        XLSX.writeFile(workbook, "MRF_PO_Report.xlsx");

    });

    $("#mrf_tbody").on("keyUp", "td.material_in_date", function () {
        $(this).closest(".material_in_by").removeClass('d-none')
    })



    $("#print_container").load('material_request_form_report1.html', function () {
        $("#mrf_print_btn1").on("click", function (event) {
            event.preventDefault();
            // TODO: handle click here


            $('#mrf_report_table1').printThis({



            });
        });


    });

    $("#po_dashboard_details").on("click", ".view_btn", function () {

        if ($(this).data("mrf_id") > 0) {
            get_material_request_form_details_print1($(this).data("mrf_id"));
        }
        else {
            salert("Warning", "Data Missing!, Try Later.", "warning");
        }

    })

});



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });


function get_po_dashboard(part, emp_id, raw_material, fdate, tdate, company) {
    $.ajax({
        url: "php/get_po_dashboard.php",
        type: "get",
        data: {
            material_query: raw_material,
            emp_query: emp_id,
            part_query: part,
            from_date: fdate,
            to_date: tdate,
            order_to_query: company,


        },
        success: function (response) {

            console.log(response);

            if (response.trim() != "error") {
                $("#po_dashboard_details").empty();
                if (response.trim() != "0 result") {
                    obj = JSON.parse(response);
                    var count = 0;

                    console.log(response);


                    obj.forEach(function (obj) {
                        count += 1;
                        var btch;
                        var batch = "";
                        var purchase = '';
                        try {
                            btch = JSON.parse(obj.batch);
                        } catch (error) {
                            btch = "no purchase entry";
                        }
                        if (btch != "no purchase entry") {
                            btch.forEach(function (item) {
                                let rev_detls;
                                let receive_detls = '';
                                var percentage = 0;
                                var progress = '';
                                if (item.batch_qty == null || item.total_received == 0 || item.total_received == null) {
                                    percentage = 0;
                                } else {
                                    percentage = (parseFloat(item.total_received) / parseFloat(item.batch_qty)) * 100;
                                }
                                percentage = Math.round(percentage);
                                if (percentage != 0) {
                                    progress = "<div class='progress'> <div class='progress-bar progress-bar-striped' role='progressbar' style='width: " + percentage + "%' aria-valuenow=" + percentage + " aria-valuemin='0' aria-valuemax='100'>" + percentage + "% </div></div>" + percentage + "% Received out of " + item.batch_qty;
                                }
                                else {
                                    progress = 'Not Received';
                                }


                                try {
                                    rev_detls = JSON.parse(item.receive_details);
                                } catch (error) {
                                    rev_detls = "No Material Received";
                                }
                                if (rev_detls != "No Material Received") {
                                    rev_detls.forEach(function (rev_item) {
                                        receive_detls += "<li  class='list-group-item text-center'><span class='fw-bold'>" + rev_item.received_by + "</span> - <span class='ps-3'>Dc No: " + rev_item.grn_dc_no + "</span><br>" + rev_item.grn_dc_date + "<span class='text-danger ps-3'>rev-qty: " + rev_item.grn_receive_qty + "</span></li>"
                                    })
                                }
                                else {
                                    receive_detls = "<li  class='list-group-item text-danger text-center'>" + item.receive_details + "</li>"
                                }
                                var status = 'pending';
                                if (item.due_sts == "active") {
                                    status = "<span class='text-primary text-success fw-bold  ps-5'>" + item.due_sts + "</span>"
                                }
                                else if (item.due_sts == "no_sts") {
                                    status = "<span class='text-primary text-warning fw-bold   ps-5'>" + item.due_sts + "</span>"
                                }
                                else {
                                    status = "<span class='text-primary text-danger fw-bold  ps-5'>" + item.due_sts + "</span>"
                                }
                                batch += "<li class='list-group-item'><div class='row'><div class='col-6 border' style='font-size:12px'>Batch Date: <b>" + item.batch_date + "</b><br>Po Date: <b>" + item.po_date + "</b><br>Po no: " + item.po_no + "(" + item.po_id + ")" + " " + status + "<br>" + progress + "</div><div class='col-6'><ul class='list-group'>" + receive_detls + "</ul></div></div></li>";

                            })
                            purchase += "<li class='list-group-item'><span class='fw-bold'>" + obj.raw_material_name + "</span><br><span class='text-danger ps-5 float-start'>" + obj.order_qty + obj.uom + "-qty </span><span class='text-success float-end'> " + (obj.supplier_name ?? '') + "</span><br>" + obj.purchase_req_by + "<span class='text-primary text-end ps-5 float-end'>" + obj.status + "</span></li>"
                        }
                        else {
                            batch = "<li class='list-group-item text-danger text-center'>" + obj.batch + "</li>"
                            purchase = "<li class='list-group-item text-danger text-center'>" + obj.batch + "</li>"
                        }

                        $("#po_dashboard_details").append("<tr><td class='text-center'>" + count + " (" + obj.mrf_id + ") " + "</td><td><ul class='list-group'><li class='list-group-item'><span class='fw-bold pe-5'>" + obj.part_name + "</span><span class='text-end'>" + obj.emp_name + "</span><br>" + obj.dated + "  <span class='text-danger ps-5'>" + obj.req_qty + obj.mrf_uom + "-qty </span><span class='text-primary ps-5'>" + obj.status + "</span></li></ul></td><td><ul class='list-group'>" + purchase + "</ul></td><td ><ul class='list-group' style='max-height: 300px; overflow-y: auto;'>" + batch + "</ul></td><td><button class='btn btn-sm btn-outline-primary border-0 view_btn' data-mrf_id=" + obj.mrf_id + "><i class='fa fa-eye'></i></button></td></tr>")
                    });


                    let grouped = {};

                    obj.forEach(item => {
                        if (!grouped[item.mrf_id]) {
                            grouped[item.mrf_id] = [];
                        }
                        grouped[item.mrf_id].push(item);
                    });

                    $("#mrf_tbody").empty();
                    let ecount = 1;
                    Object.values(grouped).forEach(group => {

                        let first = group[0];

                        let totalOrdered = parseFloat(first.rm_order_qty_total || 0);
                        let totalReceived = parseFloat(first.rm_receive_qty_total || 0);

                        if (isNaN(totalReceived)) totalReceived = 0;

                        let balance = totalOrdered - totalReceived;
                        let extraQty = totalReceived > totalOrdered ? totalReceived - totalOrdered : 0;

                        let batchData = [];
                        try {
                            batchData = JSON.parse(first.batch);
                        } catch (e) {
                            batchData = [];
                        }

                        if (batchData.length === 0) {
                            batchData = [null];
                        }

                        batchData.forEach((batch, index) => {

                            let materialInDate = "-";
                            let materialQty = 0;
                            let supplier = "Not Received";
                            let materialInBy = "";

                            if (batch) {

                                if (batch.total_received && batch.total_received > 0) {

                                    materialInDate = batch.batch_date || "-";
                                    materialQty = batch.total_received || 0;

                                    if (batch.receive_details && batch.receive_details !== "No Material Received") {
                                        try {
                                            let rd = JSON.parse(batch.receive_details);

                                            if (rd.length > 0) {
                                                supplier = `
                                                ${rd[0].grn_dc_no || ""} - 
                                                ${first.supplier_name || ""}
                                            `;
                                                materialInBy = `${rd[0].received_by || ""}`;
                                            }

                                        } catch (e) { }
                                    }
                                }
                            }

                            $("#mrf_tbody").append(`
                                <tr>
                                    ${index === 0 ? `
                                        <td class="bg-info text-center" rowspan="${batchData.length}">${ecount}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.dated.split(" ")[0]}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.mrf_id}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.raw_material_part_id || "-"}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.part_name}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.raw_material_name}</td>
                                        <td class="bg-mrf text-center" rowspan="${batchData.length}">${first.req_qty}</td>
                                        <td class="bg-mrf" rowspan="${batchData.length}">${first.req_date.split(" ")[0]}</td>

                                        <td class="bg-tally1" rowspan="${batchData.length}">${first.batch_date || "-"}</td>

                                        <td class="bg-tally2" rowspan="${batchData.length}">${first.purchase_req_by || "-"}</td>
                                        <td class="bg-po" rowspan="${batchData.length}">${first.po_date ? first.po_date.split(" ")[0] : "-"}</td>
                                        <td class="bg-po text-center" rowspan="${batchData.length}">${first.jaysan_po_id || 0}</td>
                                    ` : ""}

                                    <td class="bg-material material_in_date position-relative">${materialInDate}<span class=' material_in_by'>${materialInBy}</span></td>
                                    <td class="bg-material text-center">${materialQty}</td>
                                    <td class="bg-material">${supplier}</td>

                                    ${index === 0 ? `
                                        <td class="bg-balance text-center fw-bold" rowspan="${batchData.length}">
                                            ${balance}
                                        </td>
                                        <td class="bg-balance text-center" rowspan="${batchData.length}">
                                            ${extraQty}
                                        </td>
                                    ` : ""}
                                </tr>
                            `);
                        });

                        ecount++;
                    });

                    //    get_sales_order()
                }
                else {
                    $("#po_dashboard_details").append("<tr><td colspan='5' class='text-danger text-center'>No data found </td></tr>")
                }
            }
            else {
                salert("Error", "User ", "error");
            }

            $("#po_details_form").trigger("reset");

        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}

function get_jaysan_po_material() {


    $.ajax({
        url: "php/get_jaysan_po_material.php",
        type: "get", //send it through get method
        data: {
            jaysan_po_id: 9
        },
        success: function (response) {


            if (response.trim() != "error") {
                console.log(response);

                if (response.trim() != "0 result") {

                    var obj = JSON.parse(response);
                    var count = 0


                    obj.forEach(function (obj) {
                        console.log(obj.con_email);

                        var material = JSON.parse(obj.materials_list);


                        material.forEach(function (mat) {
                            console.log(mat.material_name);
                        })




                    });


                }
                else {
                    // $("#@id@") .append("<td colspan='0' scope='col'>No Data</td>");

                }
            }





        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });




}











function check_login() {

    if (localStorage.getItem("logemail") == null && phone_id == null) {
        window.location.replace("login.html");
    }
    else if (localStorage.getItem("logemail") == null && phone_id != null) {
        get_current_userid_byphoneid();
        $('#menu_bar').hide()
    }

    else {

    }
}


function get_current_userid_byphoneid() {
    $.ajax({
        url: "php/get_current_employee_id_byphoneid.php",
        type: "get", //send it through get method
        data: {
            phone_id: phone_id,


        },
        success: function (response) {


            if (response.trim() != "error") {
                var obj = JSON.parse(response);


                console.log(response);


                obj.forEach(function (obj) {
                    current_user_id = obj.emp_id;
                    current_user_name = obj.emp_name;
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}


function shw_toast(title, des, theme) {


    $('.toast-title').text(title);
    $('.toast-description').text(des);
    var toast = new bootstrap.Toast($('#myToast'));
    toast.show();
}

function get_millis(t) {

    var dt = new Date(t);
    return dt.getTime();
}



function get_cur_millis() {
    var dt = new Date();
    return dt.getTime();
}


function get_today_date() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();

    console.log(mins)

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T" + hour + ":" + mins;
    return today;
}

function get_today_start_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T00:00";

    return get_millis(today)

}


function get_today_end_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T23:59";

    return get_millis(today)

}

function salert(title, text, icon) {


    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date(millis) {
    var d = new Date(millis); // Parameter should be long value


    return d.toLocaleString('en-GB');

}