
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
var current_user_id = localStorage.getItem("ls_uid");
var current_user_name = localStorage.getItem("ls_uname");
var physical_stock_array = [];
$(document).ready(function () {


    $("#menu_bar").load('menu.html',
        function () {
            var lo = (window.location.pathname.split("/").pop());
            var web_addr = "#" + (lo.substring(0, lo.indexOf(".")))


            if ($(web_addr).find("a").hasClass('nav-link')) {
                $(web_addr).find("a").toggleClass('active')
            }
            else if ($(web_addr).find("a").hasClass('dropdown-item')) {
                $(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
            }


        }
    );



    check_login();

    $("#unamed").text(localStorage.getItem("ls_uname"))

    get_jaysan_po_material()
    $("#printInvoice").on("click", function (event) {
        event.preventDefault();
        // TODO: handle click here

        const win = window.open("storage%2Fpdf%2Finvoice1001.pdf", "_blank");
        // Some browsers need a delay before printing
        const printTimer = setInterval(() => {
            if (win.document.readyState === "complete") {
                clearInterval(printTimer);
                win.focus();
                win.print();
            }
        }, 500);
    });


    $("#print").on("click", function (event) {
        event.preventDefault();
        // TODO: handle click here
        var invoiceHtml = $("#invoicePreview").prop("outerHTML");

        // Encode it to protect HTML structure in POST
        var encodedHtml = encodeURIComponent(invoiceHtml);
        $.ajax({
            url: "pdf_handler.php",
            method: "POST",
            data: {
                save_path: "storage/pdf/invoice1001",
                file_name: "Invoice.pdf",
                unique_file: "no",
                header_html: "<h3 class='text-center' style='text-align: center;'>PURCHASE ORDER</h3>",
                footer_html: "<p>Generated by HS Tech Soft ERP</p>",
                body_html: encodedHtml,
                orientation: "portrait",
                paper_size: "A4",
                stream: "no",
                // email_to: "nklharish1@gmail.com",
                // email_subject: "Invoice #1001",
                // email_body: "Hello, please find attached your invoice.",
                // pdf_password: "",        // optional
                // watermark_text: ""       // optional
            },
            success: function (res) {
                console.log(res);
                if (res.download_url) {
                    // 3️⃣ open PDF and trigger browser print dialog
                    const win = window.open(res.download_url, "_blank");
                    // Some browsers need a delay before printing
                    const printTimer = setInterval(() => {
                        if (win.document.readyState === "complete") {
                            clearInterval(printTimer);
                            win.focus();
                            win.print();
                        }
                    }, 500);
                } else {
                    alert("PDF generated, but no download URL returned");
                }
            },
            error: function (xhr) {
                alert("Error: " + xhr.responseText);
            }
        });
    });


    $("#myInput_web").on("keyup", function () {
        var value = $(this).val().toLowerCase();

        $("#material_chart tr").filter(function () {
            var materialName = $(this).find("td:nth-child(2)").text().toLowerCase();
            $(this).toggle(materialName.indexOf(value) > -1);
        });
    });



    google.charts.load("current", { packages: ["corechart"] });
    google.charts.setOnLoadCallback(get_material_chart);

    // Fetch data from your PHP API
    function get_material_chart() {
        $.ajax({
            url: "php/get_material_chart.php",
            type: "GET",
            success: function (response) {
                if (response.trim() !== "error") {
                    var obj = JSON.parse(response);
                    drawChart(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChart(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Part Name', 'Total Required Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.part_name, parseInt(item.total_req_qty)]);
            $("#material_chart").append("<tr data-part_id=" + item.part_id + "><td>" + count + "</td><td>" + item.part_name + "</td><td>" + item.total_req_qty + "</td><td>" + item.frq + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Material Chart',
            is3D: true,
            // pieSliceText: 'value',
            // chartArea: { width: '65%', height: '80%' }
        };

        var chart = new google.visualization.PieChart(document.getElementById('material_piechart_3d'));
        chart.draw(data, options);
    }
    $("#material_chart").on("click", "tr", function () {
        $("#next_chart").removeClass("d-none");
        $("#part_name_head").text($(this).find("td").eq(1).text() + "  Chart")
        get_mf_company_chart($(this).data("part_id"));
        get_material_frequency_chart($(this).data("part_id"));
        // Fetch data from your PHP API

    })
    function get_mf_company_chart(part_id) {
        $.ajax({
            url: "php/get_mf_company_chart.php",
            type: "GET",
            data: {
                part_id: part_id,
            },
            success: function (response) {
                console.log(response);

                if (response.trim() !== "error") {
                    $("#company_chart").empty();
                    var obj = JSON.parse(response);
                    drawChartcompany(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChartcompany(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Company Name', 'Total Required Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.creditor_name, parseInt(item.total_req_qty)]);
            $("#company_chart").append("<tr data-part_id=" + item.part_id + "><td>" + count + "</td><td>" + item.creditor_name + "</td><td>" + item.total_req_qty + "</td><td>" + item.freq + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Company Chart',
            is3D: true,
            // pieSliceText: 'value',
            // chartArea: { width: '85%', height: '80%' }
        };

        var chart = new google.visualization.PieChart(document.getElementById('company_piechart_3d'));
        chart.draw(data, options);
    }

    function get_material_frequency_chart(part_id) {
        $.ajax({
            url: "php/get_material_frequency_chart.php",
            type: "GET",
            data: {
                part_id: part_id,
            },
            success: function (response) {
                console.log(response);

                if (response.trim() !== "error") {
                    $("#frequency_chart").empty();
                    var obj = JSON.parse(response);
                    drawChartfrequency(obj);
                } else {
                    alert("Error fetching data!");
                }
            },
            error: function (xhr) {
                console.error("AJAX Error:", xhr);
            }
        });
    }

    // Draw the Google Pie Chart
    function drawChartfrequency(dataArray) {
        // Prepare data for Google Charts
        var count = 0;
        var chartData = [['Date', 'Quantity']];
        dataArray.forEach(function (item) {
            count += 1;
            chartData.push([item.for_date, parseInt(item.total_req_qty)]);
            $("#frequency_chart").append("<tr><td>" + count + "</td><td>" + item.for_date + "</td><td>" + item.total_req_qty + "</td></tr>")
        });

        var data = google.visualization.arrayToDataTable(chartData);

        var options = {
            title: 'Frequency Chart',
            is3D: true,
            curveType: 'function',
            // pieSliceText: 'value',
            // chartArea: { width: '85%', height: '80%' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('frequency_line_chart'));
        chart.draw(data, options);
    }

    $('#company').on('input', function () {
        //check the value not empty

        if ($('#company').val() != "") {
            $('#company').autocomplete({
                //get data from databse return as array of object which contain label,value

                source: function (request, response) {

                    console.log(response);
                    $.ajax({
                        url: "php/get_po_report_search_auto.php",
                        type: "get", //send it through get method
                        data: {
                            part: request.term,
                            term: ""
                        },
                        dataType: "json",
                        success: function (data) {

                            console.log("data : " + data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.creditor_name,
                                    value: item.creditor_name,
                                    id: item.po_order_to,

                                };
                            }));

                        }

                    });
                },
                minLength: 2,
                cacheLength: 0,
                select: function (event, ui) {

                    $(this).data("po_order_to", ui.item.id);



                },

            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div><strong>" + item.label + "</strong> </div>")
                    .appendTo(ul);
            };
        }

    });

    $('#part').on('input', function () {

        // check the values not empty
        if ($('#part').val() !== "") {

            $('#part').autocomplete({
                source: function (request, response) {
                    console.log(response);

                    $.ajax({
                        url: "php/get_po_report_search_auto.php",
                        type: "get",
                        dataType: "json",
                        data: {
                            part: request.term,
                            term: "part"
                        },
                        success: function (data) {
                            console.log(data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.part_name,
                                    value: item.part_name,
                                    id: item.part_id
                                };
                            }));
                        },
                        error: function (xhr, status, error) {
                            console.error("Autocomplete error:", error);
                        }
                    });
                },
                select: function (event, ui) {
                    // When a user selects a suggestion
                    $(this).data("part_id", ui.item.id);
                    console.log("part_id :", ui.item);
                }
            })
                // ✅ Custom rendering of autocomplete dropdown
                .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                        .append("<div><strong>" + item.label + "</strong></div>")
                        .appendTo(ul);
                };
        }
    });


    $('#emp_name').on('input', function () {
        if ($('#emp_name').val() != "") {
            $('#emp_name').autocomplete({
                //get data from databse return as array of object which contain label,value

                source: function (request, response) {

                    console.log(response);
                    $.ajax({
                        url: "php/get_emp_auto.php",
                        type: "get", //send it through get method
                        data: {
                            emp_name: request.term,
                        },
                        dataType: "json",
                        success: function (data) {

                            console.log("data : " + data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.emp_name,
                                    value: item.emp_name,
                                    id: item.emp_id,

                                };
                            }));

                        }

                    });
                },
                minLength: 2,
                cacheLength: 0,
                select: function (event, ui) {

                    $(this).data("emp_id", ui.item.id);



                },

            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div><strong>" + item.label + "</strong> </div>")
                    .appendTo(ul);
            };
        }

    });

    $('#raw_material').on('input', function () {

        // check the values not empty
        if ($('#raw_material').val() !== "") {

            $('#raw_material').autocomplete({
                source: function (request, response) {
                    console.log(response);

                    $.ajax({
                        url: "php/get_po_report_search_auto.php",
                        type: "get",
                        dataType: "json",
                        data: {
                            part: request.term,
                            term: "raw"
                        },
                        success: function (data) {
                            console.log(data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.part_name,
                                    value: item.part_name,
                                    id: item.po_material_id
                                };
                            }));
                        },
                        error: function (xhr, status, error) {
                            console.error("Autocomplete error:", error);
                        }
                    });
                },
                select: function (event, ui) {
                    // When a user selects a suggestion
                    $(this).data("po_material_id", ui.item.id);
                    console.log("po_material_id :", ui.item);
                }
            })
                // ✅ Custom rendering of autocomplete dropdown
                .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                        .append("<div><strong>" + item.label + "</strong></div>")
                        .appendTo(ul);
                };
        }
    });

    $("#search").on("click", function () {
        var part = $("#part").data("part_id");
        var company = $("#company").data("po_order_to");
        var raw_material = $("#raw_material").data("po_material_id");
        var emp_id = $("#emp_name").data("emp_id");
        var fdate = $("#from_date").val();
        var tdate = $('#to_date').val();

        get_po_dashboard(part, emp_id, raw_material, fdate, tdate, company)
    })


});



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });


function get_po_dashboard(part, emp_id, raw_material, fdate, tdate, company) {
    $.ajax({
        url: "php/get_po_dashboard.php",
        type: "get",
        data: {
            material_query: raw_material,
            emp_query: emp_id,
            part_query: part,
            from_date: fdate,
            to_date: tdate,
            order_to_query: company,


        },
        success: function (response) {

            console.log(response);

            if (response.trim() != "error") {
                $("#po_dashboard_details").empty();
                var obj = JSON.parse(response);
                var count = 0;

                console.log(response);


                obj.forEach(function (obj) {
                    count += 1;
                    var btch;
                    var batch = "";
                    var purchase = '';
                    try {
                        btch = JSON.parse(obj.batch);
                    } catch (error) {
                        btch = "no purchase entry";
                    }
                    if (btch != "no purchase entry") {
                        btch.forEach(function (item) {
                            let rev_detls;
                            let receive_detls = '';
                            var percentage = 0;
                            var progress = '';
                            if (item.batch_qty == null || item.total_received == 0 || item.total_received == null) {
                                percentage = 0;
                            } else {
                                percentage = (parseFloat(item.total_received) / parseFloat(item.batch_qty)) * 100;
                            }
                            percentage = Math.round(percentage);
                            if (percentage != 0) {
                                progress = "<div class='progress'> <div class='progress-bar progress-bar-striped' role='progressbar' style='width: " + percentage + "%' aria-valuenow=" + percentage + " aria-valuemin='0' aria-valuemax='100'>" + percentage + "% </div></div>" + percentage + "% Received out of " + item.batch_qty;
                            }
                            else {
                                progress = 'Not Received';
                            }


                            try {
                                rev_detls = JSON.parse(item.receive_details);
                            } catch (error) {
                                rev_detls = "No Material Received";
                            }
                            if (rev_detls != "No Material Received") {
                                rev_detls.forEach(function (rev_item) {
                                    receive_detls += "<li  class='list-group-item text-center'><span class='fw-bold'>" + rev_item.received_by + "</span> - <span class='ps-3'>Dc No: " + rev_item.grn_dc_no + "</span><br>" + rev_item.grn_dc_date + "<span class='text-danger ps-3'>rev-qty: " + rev_item.grn_receive_qty + "</span></li>"
                                })
                            }
                            else {
                                receive_detls = "<li  class='list-group-item text-danger text-center'>" + item.receive_details + "</li>"
                            }
                            var status = 'pending';
                            if (item.due_sts == "active") {
                                status = "<span class='text-primary text-success fw-bold  ps-5'>" + item.due_sts + "</span>"
                            }
                            else if (item.due_sts == "no_sts") {
                                status = "<span class='text-primary text-warning fw-bold   ps-5'>" + item.due_sts + "</span>"
                            }
                            else {
                                status = "<span class='text-primary text-danger fw-bold  ps-5'>" + item.due_sts + "</span>"
                            }
                            batch += "<li class='list-group-item'><div class='row'><div class='col-6 border'>Batch Date: <b>" + item.batch_date + "</b><br>Po Date: <b>" + item.po_date + "</b><br>Po no: " + item.po_no + " " + status + "<br>" + progress + "</div><div class='col-6'><ul class='list-group'>" + receive_detls + "</ul></div></div></li>";

                        })
                        purchase += "<li class='list-group-item'><span class='fw-bold'>" + obj.raw_material_name + "</span><span class='text-danger ps-5'>" + obj.order_qty + "-qty </span><br>" + obj.purchase_req_by + "<span class='text-primary text-end ps-5'>" + obj.status + "</span></li>"
                    }
                    else {
                        batch = "<li class='list-group-item text-danger text-center'>" + obj.batch + "</li>"
                        purchase = "<li class='list-group-item text-danger text-center'>" + obj.batch + "</li>"
                    }

                    $("#po_dashboard_details").append("<tr><td class='text-center'>" + count + "</td><td><ul class='list-group'><li class='list-group-item'><span class='fw-bold pe-5'>" + obj.part_name + "</span><span class='text-end'>" + obj.emp_name + "</span><br>" + obj.req_date + "  <span class='text-danger ps-5'>" + obj.req_qty + "-qty </span><span class='text-primary ps-5'>" + obj.status + "</span></li></ul></td><td><ul class='list-group'>" + purchase + "</ul></td><td ><ul class='list-group' style='max-height: 300px; overflow-y: auto;'>" + batch + "</ul></td></tr>")
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }

            $("#po_details_form").trigger("reset");

        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}

function get_jaysan_po_material() {


    $.ajax({
        url: "php/get_jaysan_po_material.php",
        type: "get", //send it through get method
        data: {
            jaysan_po_id: 9
        },
        success: function (response) {


            if (response.trim() != "error") {
                console.log(response);

                if (response.trim() != "0 result") {

                    var obj = JSON.parse(response);
                    var count = 0


                    obj.forEach(function (obj) {
                        console.log(obj.con_email);

                        var material = JSON.parse(obj.materials_list);


                        material.forEach(function (mat) {
                            console.log(mat.material_name);
                        })




                    });


                }
                else {
                    // $("#@id@") .append("<td colspan='0' scope='col'>No Data</td>");

                }
            }





        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });




}











function check_login() {

    if (localStorage.getItem("logemail") == null && phone_id == null) {
        window.location.replace("login.html");
    }
    else if (localStorage.getItem("logemail") == null && phone_id != null) {
        get_current_userid_byphoneid();
        $('#menu_bar').hide()
    }

    else {

    }
}


function get_current_userid_byphoneid() {
    $.ajax({
        url: "php/get_current_employee_id_byphoneid.php",
        type: "get", //send it through get method
        data: {
            phone_id: phone_id,


        },
        success: function (response) {


            if (response.trim() != "error") {
                var obj = JSON.parse(response);


                console.log(response);


                obj.forEach(function (obj) {
                    current_user_id = obj.emp_id;
                    current_user_name = obj.emp_name;
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}


function shw_toast(title, des, theme) {


    $('.toast-title').text(title);
    $('.toast-description').text(des);
    var toast = new bootstrap.Toast($('#myToast'));
    toast.show();
}

function get_millis(t) {

    var dt = new Date(t);
    return dt.getTime();
}



function get_cur_millis() {
    var dt = new Date();
    return dt.getTime();
}


function get_today_date() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();

    console.log(mins)

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T" + hour + ":" + mins;
    return today;
}

function get_today_start_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T00:00";

    return get_millis(today)

}


function get_today_end_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T23:59";

    return get_millis(today)

}

function salert(title, text, icon) {


    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date(millis) {
    var d = new Date(millis); // Parameter should be long value


    return d.toLocaleString('en-GB');

}