
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
var current_user_id = localStorage.getItem("ls_uid");
var current_user_name = localStorage.getItem("ls_uname");
var physical_stock_array = [];
var company = '';
var company_name = '';
var consignee = '';
var supplier = '';
var terms = '';
var po_no = '';
var po_delivery_to = '';
var po_order_to = '';
var gst_details = '';
var gst_amount_details = '0';
var gst_0 = [];
var gst_5 = [];
var gst_12 = [];
var gst_18 = [];
var gst_28 = [];
var gst_40 = [];
var sub_but = 0;
var po_id = '';
$(document).ready(function () {


    $("#menu_bar").load('menu.html',
        function () {
            var lo = (window.location.pathname.split("/").pop());
            var web_addr = "#" + (lo.substring(0, lo.indexOf(".")))


            if ($(web_addr).find("a").hasClass('nav-link')) {
                $(web_addr).find("a").toggleClass('active')
            }
            else if ($(web_addr).find("a").hasClass('dropdown-item')) {
                $(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
            }


        }
    );



    check_login();

    $("#unamed").text(localStorage.getItem("ls_uname"))


    $("#po_report_search").on("keyup", function () {
        var value = $(this).val().toLowerCase();

        $("#po_report tr").filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
        });
    });

    $("#po_list_search").on("keyup", function () {
        var value = $(this).val().toLowerCase();

        $("#get_po_list tr").filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
        });
    });


    $("#po_dash_search").on("keyup", function () {
        var value = $(this).val().toLowerCase();

        $("#po_dashboard_table tr").filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
        });
    });




    // mail function
    $("#mail_print").on("click", function (e) {
        e.preventDefault();

        $(this).prop("disabled", true);

        var po_materials = [];
        var allApproved = true;

        $("#selected_materials").find("tr:not(:last-child)").each(function () {
            let apprv = $(this).data("approve");
            if (apprv == '0') {
                // alert("Some PO items are not approved. Please approve them first.");
                allApproved = false;

            }

            var batch_id = $(this).data("batch_id");
            let material_part_id = $(this).data("material_part_id");
            console.log(material_part_id);

            let quantity = $(this).data("batch_qty");
            let rate = $(this).find("td").eq(4).text().trim();
            let due_date = $(this).find("td").eq(2).text().trim();
            let disc = $(this).data("discount");


            po_materials.push({
                batch_id: batch_id,
                po_material_id: material_part_id,
                qty: quantity,
                material_rate: rate,
                is_approved: apprv,
                due_on: due_date,
                disc: disc,
            });
        });
        if (allApproved == false) {
            alert("Some PO items are not approved. Please approve them first.");

        }
        let po_terms = $("#terms_of_delivery_input").val();
        console.log(po_terms);
        let po_no = $("#po_no").val();
        if (allApproved) {
            // TODO: handle click here
            $("#overlay").fadeIn();

            var invoiceHtml = $("#preview_Purchase").prop("outerHTML");
            var company_con = company_name.replace(/[^a-zA-Z0-9]+/g, '_');

            // Optional: remove leading/trailing underscores
            company_con = company_con.replace(/^_+|_+$/g, '');
            // Encode it to protect HTML structure in POST
            var encodedHtml = encodeURIComponent(invoiceHtml);
            $.ajax({
                url: "pdf_handler.php",
                method: "POST",

                data: {
                    save_path: "storage/purchase_order/po_" + company_con,
                    file_name: "po_" + company_con + ".pdf",
                    unique_file: "yes",
                    header_html: "<h3 class='text-center' style='text-align: center;'>PURCHASE ORDER</h3>",
                    footer_html: "<p>Generated by HS Tech Soft ERP</p>",
                    body_html: encodedHtml,
                    orientation: "portrait",
                    paper_size: "A4",
                    stream: "no",
                    // email_to: "sanjay040611@gmail.com",
                    // email_subject: "Invoice #1001",
                    // email_body: "Hello, please find attached your invoice.",
                    pdf_password: "",        // optional
                    watermark_text: ""       // optional
                },
                success: function (res) {
                    console.log(res);

                    insert_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, "1", res.download_url, po_no);
                },
                error: function (xhr) {
                    alert("Error: " + xhr.responseText);
                },
                // complete: function () {
                //     $("#overlay").fadeOut();
                //     $("#mail_print").prop("disabled", false);
                // }
            });
        }
        else {
            insert_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, "0", "", po_no);
        }

    });


    $("#update_po").on("click", function (e) {
        e.preventDefault();

        $(this).prop("disabled", true);

        var po_materials = [];
        var allApproved = true;

        $("#selected_materials").find("tr:not(:last-child)").each(function () {
            let apprv = $(this).data("approve");
            if (apprv == '0') {
                // alert("Some PO items are not approved. Please approve them first.");
                allApproved = false;

            }

            var batch_id = $(this).data("batch_id");
            let material_part_id = $(this).data("material_part_id");

            console.log(material_part_id);
            let quantity = $(this).data("batch_qty");
            let rate = $(this).find("td").eq(4).text().trim();
            let due_date = $(this).find("td").eq(2).text().trim();
            let disc = $(this).data("discount");


            po_materials.push({
                batch_id: batch_id,
                po_material_id: material_part_id,
                qty: quantity,
                material_rate: rate,
                is_approved: apprv,
                due_on: due_date,
                disc: disc,
            });
        });
        if (allApproved == false) {
            alert("Some PO items are not approved. Please approve them first.");

        }
        let po_terms = $("#terms_of_delivery_input").val();
        let po_no = $("#po_no").val();
        if (allApproved) {
            // TODO: handle click here
            $("#overlay").fadeIn();

            var invoiceHtml = $("#preview_Purchase").prop("outerHTML");
            var company_con = company_name.replace(/[^a-zA-Z0-9]+/g, '_');

            // Optional: remove leading/trailing underscores
            company_con = company_con.replace(/^_+|_+$/g, '');
            // Encode it to protect HTML structure in POST
            var encodedHtml = encodeURIComponent(invoiceHtml);
            $.ajax({
                url: "pdf_handler.php",
                method: "POST",



                data: {
                    save_path: "storage/purchase_order/po_" + company_con,
                    file_name: "po_" + company_con,
                    unique_file: "yes",
                    header_html: "<h3 class='text-center' style='text-align: center;'>PURCHASE ORDER</h3>",
                    footer_html: "<p>Generated by HS Tech Soft ERP</p>",
                    body_html: encodedHtml,
                    orientation: "portrait",
                    paper_size: "A4",
                    stream: "no",
                    // email_to: "sanjay040611@gmail.com",
                    // email_subject: "Invoice #1001",
                    // email_body: "Hello, please find attached your invoice.",
                    pdf_password: "",        // optional
                    watermark_text: ""       // optional
                },
                success: function (res) {
                    console.log(res);

                    update_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, "1", res.download_url, po_id, po_no);
                },
                error: function (xhr) {
                    alert("Error: " + xhr.responseText);
                },
                // complete: function () {
                //     $("#overlay").fadeOut();
                //     $("#update_po").prop("disabled", false);
                // }
            });
        }
        else {
            update_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, "0", "", po_id, po_no);
        }

    });

    get_mrf_po_details();
    get_po_list();


    $("#po_report").on("click", " tr ", function (e) {
        e.preventDefault();

        $("#purchase_order_details").empty();
        clear_gst_arrays();
        $("#preview_Purchase").addClass("d-none");
        $("#po_submit").removeClass("d-none");

        $("#mail_print").addClass("d-none");
        $("#update_po").addClass("d-none");
        get_mrf_po_basic_details($(this).data("mrf_id"));
        $("#company_name").text("Company Name: " + $(this).closest("tr").find("td").eq(2).text());
        get_mrf_po_company_wise($(this).data("po_order_to"));
    })

    $("#po_dashboard_table").on("input", "tr td", function () {
        var order_qnty = parseInt($(this).text());

        var original_qnty = parseInt($(this).closest("tr").find("td").eq(3).data("batch_qty"));


        if (order_qnty > original_qnty && $(this).index() == 3) {
            $(this).text($(this).closest("tr").find("td").eq(3).data("batch_qty"))
        }
    })

    $("#po_dashboard_table").on("change", ".material-check", function () {


        let row = $(this).closest("tr");
        let isChecked = $(this).is(":checked");
        let batch_id = row.data("batch_id");
        let batch_qty = row.find("td:eq(3)").text();
        let uom = row.data("uom");
        let raw_material_rate = row.data("raw_material_rate");
        let gst_rate = row.data("gst_rate");
        var this_row = $(this);


        var total = 0;
        var raw_material_total_amount = 0;


        console.log("change");


        get_po_order_total(this_row)

        // if (gst_0.length > 0) {
        // var total = 0
        //     $.each(gst_0, function (key, val) {
        //         var gst_text = "input cgst @0%"+'<br>'+"input sgst @0%";
        //         gst_details += gst_text + '<br>';
        //         total += val
        //     });
        //    total = total *0.6;
        //    gst_amount_details +=  total.toFixed(2) +   '<br>' + total.toFixed(2) + '<br>' 
        // }



    });




    $("#po_submit").on("click", function (e) {
        e.preventDefault();

        $("#terms_of_delivery_input").val(terms);
        $("#po_no").val(po_no);

        // $(this).addClass("d-none");

        if ($("#selected_materials tr").length == 0) {
            salert("Error", "Please select at least one material.", "error");
            return;
        }

        else {
            $("#terms").modal("show");

        }
    });

    $("#terms_btn").on("click", function (e) {
        e.preventDefault();
        $("#preview_Purchase").removeClass("d-none");

        $("#po_submit").addClass("d-none");
        let terms = $("#terms_of_delivery_input").val().trim();
        if (sub_but == 1) {
            $("#update_po").removeClass("d-none")
        }
        else {
            $("#mail_print").removeClass("d-none")
        }
        $("#voucher_no").text("Voucher No: " + $("#po_no").val())
        $("#invoice_to").html("Invoice To <br>" + company);
        $("#consignee").html(consignee);
        $("#supplier").html(supplier);

        // let tr_data =  $("#selected_materials").closest("tr");

        var count = 0;

        if (gst_0.length > 0) {
            var total_gst = 0
            $.each(gst_0, function (key, val) {

                total_gst += val
            });
            var gst_text = "input cgst @0%" + '<br>' + "input sgst @0%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'
            console.log("gst_0 " + gst_amount_details);

        }

        if (gst_5.length > 0) {
            var total_gst = 0
            $.each(gst_5, function (key, val) {

                total_gst += val
            });
            var gst_text = "input cgst @2.5%" + '<br>' + "input sgst @2.5%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0.025;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'
            console.log("gst_5 " + gst_amount_details);

        }
        if (gst_12.length > 0) {
            var total_gst = 0
            $.each(gst_12, function (key, val) {

                total_gst += val
            });
            var gst_text = "input cgst @6%" + '<br>' + "input sgst @6%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0.06;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'
            console.log("gst_12 " + gst_amount_details);

        }
        if (gst_18.length > 0) {
            var total_gst = 0
            $.each(gst_18, function (key, val) {
                total_gst += val
            });
            var gst_text = "input cgst @9%" + '<br>' + "input sgst @9%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0.09;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'
        }

        if (gst_28.length > 0) {
            var total_gst = 0
            $.each(gst_28, function (key, val) {
                total_gst += val
            });
            var gst_text = "input cgst @14%" + '<br>' + "input sgst @14%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0.14;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'

        }
        if (gst_40.length > 0) {
            var total_gst = 0
            $.each(gst_40, function (key, val) {
                total_gst += val
            });
            var gst_text = "input cgst @20%" + '<br>' + "input sgst @20%";
            gst_details += gst_text + '<br>';
            total_gst = total_gst * 0.20;
            gst_amount_details += total_gst.toFixed(2) + '<br>' + total_gst.toFixed(2) + '<br>'

        }




        $("#selected_materials").find("tr").each(function () {

            count = count + 1;
            let materials = $(this).find("td").eq(0).text();
            let Due = $(this).find("td").eq(2).text();
            let quantity = $(this).find("td").eq(3).text();
            let rate = $(this).find("td").eq(4).text();
            let amount = $(this).find("td").eq(5).text();
            let discount = $(this).data("discount");
            let uom = $(this).data("uom");
            let approve = $(this).data("approve");
            console.log(approve);

            if (materials !== "" && Due !== "" && quantity !== "" && rate !== "" && amount !== "") {
                $("#purchase_order_details").append("<tr data-approve=" + approve + "><td  class='text-center' style='max-width: 5px; text-align: center;'>" + count + "</td><td>" + materials + "</td><td>" + Due + "</td><td>" + quantity + "</td><td>" + rate + "</td><td>" + uom + "</td><td>" + discount + "</td><td>" + amount + "</td></tr>");
            }
            // if (count == $("#selected_materials tr").length - 1) {

            // }
        });
        let final_total = (2 * parseFloat(gst_amount_details)) + parseFloat($("#raw_material_total_amount_id").text());
        let less = Math.round(final_total) - final_total;
        let safeTotal = Math.min(Math.round(final_total), 999999999999999);
        let words = numberToWords(safeTotal);

        console.log(words);

        $("#purchase_order_details").append("<tr><th scope='col' colspan='7' class='text-center' style='text-align:center'>Total</th>\<td id='raw_material_total_amount_id'>" + $("#raw_material_total_amount_id").text() + "</td></tr>" +
            "<tr><td id='gst_details' colspan='7'>" + gst_details + "</td><td id='gst_amount_details'>" + gst_amount_details + "</td></tr>" +
            "<tr><th scope='col'  colspan='7'>Rounded Off</th><td id='less'>" + less.toFixed(2) + "</td></tr>" +
            "<tr><th scope='col' colspan='3'>Net Total</th><td>" + $("#total").text() + "</td><td></td><td></td><td></td><td id='final_total'>" + Math.round(final_total).toFixed(2) + "</td></tr>" +
            "<tr><td colspan='8'>Amount Chargeable (in words)<span class='eoe'>E.& O.E</span><br><b> INR " + words + "</b></td></tr>" +
            "<tr><td colspan='4'>Remark <br>Po against by proforma</td><td colspan='4' class='text-end'><b>for JAYSAN AGRI INDUSTRIAL</b><br><br>Signature</td></tr>"
        );
        if (terms === "") {
            salert("Error", "Please enter the terms of delivery.", "error");
            return;
        }

        $("#terms_of_delivery").html("Terms of Delivery:<br>" + terms);
        $("#terms").modal("hide");
        // salert("Success", "Terms of delivery set successfully.", "success");




    });

    $("#extra_po_add").on("click", function (e) {
        e.preventDefault();

        $("#po_submit").removeClass("d-none");
        $("#update_po").addClass("d-none");
        let materials = $("#material").val().trim();
        let Due = $("#due_date").val().trim();
        let quantity = $("#quantity").val().trim();
        let uom = $("#uom").val().trim();
        let rate = $("#rate").val().trim();
        let discount = $("#discount").val().trim();
        let gst_rate = $("#material").data("gst_rate");
        console.log(gst_rate);


        if (materials == "" || Due == "" || quantity == "" || uom == "" || rate == "" || discount == "" || gst_rate == "") {
            salert("Error", "Please fill all the fields.", "error");
            return;
        }
        // let amnt = (rate * quantity);
        // amnt = amnt - (amnt * (discount / 100));
        // console.log("amount " + amnt);

        // let count = $("#selected_materials tr").length;
        // let extra_po_data = "<tr data-batch_id='0' data-approved='0' data-batch_qty='" + quantity + "' data-uom='" + uom + "' data-discount='" + discount + "'>" +
        //     "<td>" + materials + "</td><td>-</td>" +
        //     "<td>" + Due + "</td>" +
        //     "<td>" + quantity + " " + uom + "</td>" +
        //     "<td>" + rate + "</td>" +
        //     "<td>" + amnt + "</td>" +
        //     "</tr>";
        // if ($("#selected_materials tr#totalRow").length > 0) {
        //     $("#selected_materials tr#totalRow").before(extra_po_data);
        // } else {
        //     $("#selected_materials").append(extra_po_data);
        // }

        get_po_order_total();
        $("#extra_po_order_form")[0].reset();
    });

    $("#selected_materials").on("click", ".fa-trash", function () {
        const row = $(this).closest("tr");
        const materialId = row.data("batch_id");

        $("#po_dashboard_table tr[data-batch_id='" + materialId + "']")
            .find("input[type='checkbox']")
            .prop("checked", false);
        row.remove();

        $("#selected_materials tr#totalRow").remove();
        clear_gst_arrays();
        $("#selected_materials tr[data-batch_id]").each(function () {
            let amount = parseFloat($(this).find("td:eq(5)").text()) || 0;


            switch ($(this).data("gst_rate")) {
                case 0:
                    gst_0.push(amount);
                    break;
                case 5:
                    gst_5.push(amount);
                    break;
                case 12:
                    gst_12.push(amount);
                    break;
                case 18:
                    gst_18.push(amount);
                    break;
                case 28:
                    gst_28.push(amount);
                    break;
                case 40:
                    gst_40.push(amount);
                    break;

                default:
                    break;
            }



        });

        let total_qty = 0;
        let total_amount = 0;
        $("#selected_materials tr").each(function () {
            total_qty += parseFloat($(this).data("batch_qty"));
            total_amount += parseFloat($(this).find("td").eq(5).text());
        });

        if (($("#selected_materials tr#totalRow").length === 0) && $("#selected_materials tr").length > 0) {

            console.log("hiiiii");

            $("#selected_materials").append(
                "<tr  id ='totalRow'><th scope='col' colspan='3'>Total</th><td id='total'>" + total_qty + "</td><td></td><td id='raw_material_total_amount_id' colspan='2'>" + total_amount + "</td></tr>"
            );
        }
        else {

            $("#total").text(total_qty);
            $("#raw_material_total_amount_id").text(total_amount);
        }
        $("#purchase_order_details").empty();

        $("#preview_Purchase").addClass("d-none");

    });


    $('#material').on('input', function () {
        //check the value not empty
        if ($('#material').val() != "") {
            $('#material').autocomplete({
                //get data from databse return as array of object which contain label,value

                source: function (request, response) {
                    $.ajax({
                        url: "php/mrf_partname_autocomplete.php",
                        type: "get", //send it through get method
                        data: {
                            part_name: $("#material").val(),


                        },
                        dataType: "json",
                        success: function (data) {

                            console.log(data);
                            response($.map(data, function (item) {
                                return {
                                    label: item.part_name,
                                    value: item.part_name,
                                    id: item.part_id,
                                    part_name: item.part_name,
                                    gst: item.gstrate
                                };
                            }));

                        }

                    });
                },
                minLength: 2,
                cacheLength: 0,
                select: function (event, ui) {

                    $(this).data("material_part_id", ui.item.id);
                    // $(this).data("gst_rate", ui.item.gst);
                    $('#material').data("gst_rate", ui.item.gst);
                    // $('#part_name_out').val(ui.item.part_name)
                    // get_bom(ui.item.id)


                },

            }).autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div><strong>" + item.part_name + "</strong></div>")
                    .appendTo(ul);
            };
        }

    });


    $("#get_po_list").on("click", "tr td i.fa-pen-to-square", function () {
        po_id = $(this).data("po_id");
        console.log(po_id);

        sub_but = 1;
        get_jaysan_po_material(po_id);
        $("#po_submit").removeClass("d-none");
        $("#mail_print").addClass("d-none");
        $("#update_po").addClass("d-none");


    })

    $("#get_po_list").on("click", "tr td i.fa-print", function () {
        let path = $(this).data("po_path");
        console.log(path);

        window.open(path, '_blank');
    })

});


function get_jaysan_po_material(po_id) {
    $.ajax({
        url: "php/get_jaysan_po_material.php",
        type: "get", //send it through get method
        data: {
            jaysan_po_id: po_id,
        },
        success: function (response) {
            console.log(response);


            $("#po_dashboard_table").empty();

            $("#selected_materials").empty();

            if (response.trim() != "error") {
                var obj = JSON.parse(response);


                obj.forEach(function (obj) {
                    company_name = obj.con_name
                    $("#company_name").text("Company Name: " + obj.sub_name);
                    po_order_to = obj.po_order_to;
                    po_delivery_to = obj.po_delivery_to;
                    var materials_list = obj.materials_list;

                    company = obj.company_address;
                    terms = obj.po_terms;
                    po_no = obj.po_no;
                    consignee = "Consignee (Ship to) <br>" + obj.con_name + "<br>" + obj.con_addr + "<br>e-mail : " + obj.con_email + "<br>GSTIN/UIN : " + obj.con_gst + "<br>State Name : " + obj.con_state_name;
                    supplier = "Supplier (Bill from) <br>" + obj.sub_name + "<br>" + obj.sub_addr + "<br>GSTIN/UIN : " + obj.sub_gst + "<br>State Name : " + obj.sub_state_name + "<br>Contact person : " + obj.sub_contact_person + "<br>Contact : " + obj.sub_contact + "<br>e-mail : " + obj.sub_email;


                    var mat = JSON.parse(materials_list);

                    mat.forEach(function (mat) {
                        console.log(mat.material_id);

                        $("#po_dashboard_table").append(
                            "<tr data-batch_id='" + mat.batch_id + "' data-uom='" + mat.uom + "' data-raw_material_rate='" + mat.material_rate + "' data-gst_rate='" + mat.gst + "' data-approve='" + mat.is_approved + "' data-material_part_id='" + mat.material_id + "'>" +
                            "<td><input class='form-check-input material-check' type='checkbox' value='" + mat.batch_id + "'></td>" +
                            "<td>" + mat.material_name + "</td>" +
                            "<td>" + mat.original_qty + "</td>" +
                            "<td data-batch_qty='" + mat.original_qty + "' contenteditable='true'>" + mat.original_qty + "</td>" +
                            "<td contenteditable='true'>" + mat.discount + "</td>" +
                            "<td>" + mat.batch_date + "</td>" +
                            "<td><input type='date'disabled class='form-control date-input' value='" + mat.due_on + "'></td>" +
                            "</tr>"
                        );
                    })

                });

                $("#po_dashboard_table .material-check").prop("checked", true).trigger("change");
                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        },
        complete: function () {

        }
    });
}

function get_po_order_total(row_ref) {

    let total_qty = 0;
    let total_amount = 0;


    clear_gst_arrays();

    let batch_id = '';
    let batch_qty = '';
    let uom = '';
    let raw_material_rate = '';
    let gst_rate = '';
    let row = '';
    let discount = 0;
    let due_date = '';
    let batch_date = '-';
    let materials = '';
    let approve = '';
    let material_part_id = '';
    let isChecked = false;



    if (row_ref === undefined) {

        batch_id = "";
        batch_qty = $("#quantity").val();
        isChecked = true;
        uom = $("#uom").val();
        raw_material_rate = $("#rate").val();
        discount = $("#discount").val();
        due_date = $("#due_date").val();
        materials = $("#material").val();
        gst_rate = $("#material").data("gst_rate");
        material_part_id = $("#material").data("material_part_id");
        console.log(material_part_id);
        approve = '0';

    }
    else {

        row = row_ref.closest("tr");
        isChecked = row_ref.is(":checked");
        batch_id = row.data("batch_id");
        batch_qty = row.find("td:eq(3)").text();
        uom = row.data("uom");
        raw_material_rate = row.data("raw_material_rate");
        discount = row.find("td:eq(4)").text();
        gst_rate = row.data("gst_rate");
        due_date = row.find("td:eq(6)").find('input').val();
        batch_date = row.find("td:eq(5)").text();
        materials = row.find("td:eq(1)").text();
        material_part_id = row.data("material_part_id");
        console.log(material_part_id);

        console.log(row.is(["data-approve"]));

        if (row.data("approve") != undefined) {
            approve = row.data("approve");
        }
        else {
            approve = '1';
        }


    }

    $("#selected_materials tr#totalRow").remove();

    if (!isChecked) {
        $("#selected_materials tr[data-batch_id='" + batch_id + "']").remove();
        $("#selected_materials tr#totalRow").remove();

        row.find("td").eq(3).prop("contenteditable", true);
        row.find("td").eq(4).prop("contenteditable", true);
        $("#preview_Purchase").addClass("d-none");
        $("#purchase_order_details").empty();
        clear_gst_arrays();

    }
    else {
        // row.find("td").eq(3).prop("contenteditable", false);
        // row.find("td").eq(4).prop("contenteditable", false);
        let amnt = (raw_material_rate * batch_qty);
        amnt = amnt - (amnt * (discount / 100));
        let newRow = "<tr data-batch_id='" + batch_id + "' data-batch_qty='" + batch_qty + "' data-gst_rate='" + gst_rate + "'data-uom='" + uom + "' data-discount='" + discount + "' data-approve='" + approve + "' data-material_part_id='" + material_part_id + "'>" +
            "<td>" + materials + "</td>" +
            "<td>" + batch_date + "</td>" +
            "<td>" + due_date + "</td>" +
            "<td>" + batch_qty + " " + uom + "</td>" +
            "<td>" + raw_material_rate + "</td>" +
            "<td>" + amnt + "</td>" +
            "<td><i class='fa fa-trash'></i></td>" +
            "</tr>";

        if ($("#selected_materials tr#totalRow").length > 0) {
            $("#selected_materials tr#totalRow").before(newRow);
        } else {
            $("#selected_materials").append(newRow);
        }
        clear_gst_arrays();
        $("#preview_Purchase").addClass("d-none");
        $("#purchase_order_details").empty();

    }


    $("#selected_materials tr[data-batch_id]").each(function () {
        let amount = parseFloat($(this).find("td:eq(5)").text()) || 0;


        switch ($(this).data("gst_rate")) {
            case 0:
                gst_0.push(amount);
                break;
            case 5:
                gst_5.push(amount);
                break;
            case 12:
                gst_12.push(amount);
                break;
            case 18:
                gst_18.push(amount);
                break;
            case 28:
                gst_28.push(amount);
                break;
            case 40:
                gst_40.push(amount);
                break;

            default:
                break;
        }



    });

    $("#selected_materials tr").each(function () {
        total_qty += parseFloat($(this).data("batch_qty"));
        total_amount += parseFloat($(this).find("td").eq(5).text());
    });

    if (($("#selected_materials tr#totalRow").length === 0) && $("#selected_materials tr").length > 0) {


        $("#selected_materials").append(
            "<tr  id ='totalRow'><th scope='col' colspan='3'>Total</th><td id='total'>" + total_qty + "</td><td></td><td id='raw_material_total_amount_id' colspan='2'>" + total_amount + "</td></tr>"
        );
    } else {

        $("#total").text(total_qty);
        $("#raw_material_total_amount_id").text(total_amount);
    }
}

function numberToWords(num) {
    const a = [
        '', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
        'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen',
        'Seventeen', 'Eighteen', 'Nineteen'
    ];
    const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

    function inWords(n) {
        if (n === 0) return '';
        if (n < 20) return a[n];
        if (n < 100) return b[Math.floor(n / 10)] + (n % 10 ? " " + a[n % 10] : "");
        if (n < 1000) return a[Math.floor(n / 100)] + " Hundred" + (n % 100 ? " " + inWords(n % 100) : "");
        if (n < 1000000) return inWords(Math.floor(n / 1000)) + " Thousand" + (n % 1000 ? " " + inWords(n % 1000) : "");
        if (n < 1000000000) return inWords(Math.floor(n / 1000000)) + " Million" + (n % 1000000 ? " " + inWords(n % 1000000) : "");
        if (n < 1000000000000) return inWords(Math.floor(n / 1000000000)) + " Billion" + (n % 1000000000 ? " " + inWords(n % 1000000000) : "");

        return inWords(Math.floor(n / 1000000000000)) + " Trillion" + (n % 1000000000000 ? " " + inWords(n % 1000000000000) : "");
    }

    const result = inWords(num).trim();
    return result || "Zero";
}



function clear_gst_arrays() {
    gst_0 = [];
    gst_5 = [];
    gst_12 = [];
    gst_18 = [];
    gst_28 = [];
    gst_40 = [];
    gst_details = '';
    gst_amount_details = '0';

}


function get_mrf_po_details() {
    $.ajax({
        url: "php/get_mrf_po_details.php",
        type: "get", //send it through get method
        data: {


        },
        success: function (response) {

            console.log(response);

            if (response.trim() != "error") {
                var obj = JSON.parse(response);
                var count = 0;


                obj.forEach(function (obj) {

                    var order_type_badge = "";


                    if (obj.order_type == "Regular") {
                        order_type_badge = "<span class='ms-1 badge bg-success'>R</span>"
                    }
                    else if (obj.order_type == "Emergency") {
                        order_type_badge = "<span class='ms-1 blink badge bg-danger'>E</span>"
                    }


                    var commitment_sts = "";
                    if (obj.approx_del_date != null && obj.approx_del_date != "" && obj.approx_del_date != "0" && obj.approx_del_date != "undefined") {
                        commitment_sts = obj.approx_del_date
                    }
                    else {
                        commitment_sts = "<i class='fa-solid fa-hourglass-start'></i>"
                        // commitment_sts = obj.commitment_date
                    }
                    var balance = '';
                    var bal = parseInt(obj.batch_qty) - ((obj.pre_po_qty == null) ? '0' : parseInt(obj.pre_po_qty))
                    if (bal != obj.batch_qty) {
                        balance = "Ord: <b>" + ((obj.pre_po_qty == null) ? '0' : obj.pre_po_qty) + "</b><br>Balance: <b>" + bal + "</b> "
                    }
                    else {
                        balance = '';
                    }
                    count = count + 1;
                    $("#po_report").append("<tr data-po_order_to='" + obj.po_order_to + "' data-mrf_id='" + obj.mrf_id + "' ><td>" + count + "</td><td><ul class='list-group ' ><li class='list-group-item '> <div class='d-flex justify-content-between align-content-around'> <div class = 'small'><span class='text-bg-light fw-bold'>  " + obj.mrf_id + " Batch: " + obj.batch_id + ". </span>" + obj.part_name + order_type_badge + "<span class='ms-1 small  badge bg-primary'>" + obj.total_part_count + "</span></div> <div> <button class='btn btn-outline-danger btn-sm border-0 history_btn' " +
                        "data-bs-toggle='popover' data-bs-html='true' data-bs-placement='left' " +
                        "data-history=\"" + obj.form_history.replace(/"/g, '&quot;') + "\" title='History'>" +
                        "<i class='fa fa-clock-o' aria-hidden='true'></i></button></div></div></li><li class='list-group-item '><div class='d-flex justify-content-between align-content-around'> <div class='small'>" + obj.req_date_format + " </div> <div class='small'>" + commitment_sts + "  </div></div></li></ul></td><td id='order_to'>" + obj.order_to + "</td><td>" + obj.raw_material_part_id + "</td><td>" + obj.batch_date + "</td><td>" + obj.batch_qty_with_uom + "<br>" + balance + "</td></tr>");
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}


function get_mrf_po_company_wise(order_to) {
    $.ajax({
        url: "php/get_mrf_po_company_wise.php",
        type: "get", //send it through get method
        data: {
            order_to_id: order_to,
        },
        success: function (response) {
            console.log(response);


            $("#po_dashboard_table").empty();

            $("#selected_materials").empty();

            if (response.trim() != "error") {
                var obj = JSON.parse(response);



                obj.forEach(function (obj) {
                    console.log(obj.material_part_id);

                    po_order_to = obj.po_order_to;
                    po_delivery_to = obj.po_delivery_to;
                    var balance = '';
                    if (obj.bal_qty != obj.batch_qty) {
                        balance = "Ord: <b>" + obj.pre_qty + "</b><br>Balance: <b>" + obj.bal_qty + "</b> "
                    }
                    else {
                        balance = '';
                    }
                    $("#po_dashboard_table").append(
                        "<tr data-batch_id='" + obj.batch_id + "' data-uom='" + obj.uom + "' data-material_part_id='" + obj.material_part_id + "' data-raw_material_rate='" + obj.raw_material_rate + "' data-gst_rate='" + obj.gstrate + "'>" +
                        "<td><input class='form-check-input material-check' type='checkbox' value='" + obj.batch_id + "'></td>" +
                        "<td>" + obj.raw_material_part_id + "</td>" +
                        "<td>" + obj.batch_qty_with_uom + "<br>" + balance + "</td>" +
                        "<td data-batch_qty='" + obj.bal_qty + "' contenteditable='true'>" + obj.bal_qty + "</td>" +
                        "<td contenteditable='true'>0</td>" +
                        "<td>" + obj.batch_date + "</td>" +
                        "<td><input type='date'disabled class='form-control date-input' value='" + obj.approx_due_date + "'></td>" +
                        "</tr>"
                    );
                });


                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}

function get_mrf_po_basic_details(mrf_id) {
    $.ajax({
        url: "php/get_mrf_po_basic_details.php",
        type: "get", //send it through get method
        data: {
            mrf_id: mrf_id,

        },
        success: function (response) {

            console.log(response);

            if (response.trim() != "error") {
                var obj = JSON.parse(response);


                obj.forEach(function (obj) {
                    company_name = obj.con_name
                    company = obj.company_address;
                    terms = obj.terms;
                    po_no = obj.max_po_no;
                    consignee = "Consignee (Ship to) <br>" + obj.con_name + "<br>" + obj.con_addr + "<br>e-mail : " + obj.con_email + "<br>GSTIN/UIN : " + obj.con_gst + "<br>State Name : " + obj.con_state_name;
                    supplier = "Supplier (Bill from) <br>" + obj.sub_name + "<br>" + obj.sub_addr + "<br>GSTIN/UIN : " + obj.sub_gst + "<br>State Name : " + obj.sub_state_name + "<br>Contact person : " + obj.sub_contact_person + "<br>Contact : " + obj.sub_contact + "<br>e-mail : " + obj.sub_email;
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}


function update_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, po_email, po_path, po_id, po_no) {
    console.log(po_order_to);
    console.log(po_materials);
    console.log(po_email);
    console.log(po_path);
    console.log(po_terms);


    $.ajax({
        url: "php/update_purchase_order.php",
        type: "post", //send it through get method
        data: {
            po_order_to: po_order_to,
            po_delivery_to: po_delivery_to,
            po_terms: po_terms,
            po_materials: po_materials,
            po_email: po_email,
            po_path: po_path,
            po_id: po_id,
            po_no: po_no,


        },
        success: function (response) {


            console.log(response);
            if (response.trim() == "ok") {
                location.reload();

            }

            else {
                salert("Error", "User ", "error");
                // location.reload();
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        },
        complete: function () {
            //  Hide overlay and re-enable button
            $("#overlay").fadeOut();
            $("#update_po").prop("disabled", false);
        }
    });
}


function insert_purchase_order(po_order_to, po_delivery_to, po_terms, po_materials, po_email, po_path, po_no) {
    console.log(po_order_to);
    console.log(po_materials);
    console.log(po_email);
    console.log(po_path);
    console.log("sds" + po_no);


    $.ajax({
        url: "php/insert_purchase_order.php",
        type: "post", //send it through get method
        data: {
            po_order_to: po_order_to,
            po_delivery_to: po_delivery_to,
            po_terms: po_terms,
            po_materials: po_materials,
            po_email: po_email,
            po_path: po_path,
            po_no: po_no,


        },
        success: function (response) {


            console.log(response);
            if (response.trim() == "ok") {
                location.reload();

            }

            else {
                salert("Error", "User ", "error");
                // location.reload();
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        },
        complete: function () {
            //  Hide overlay and re-enable button
            $("#overlay").fadeOut();
            $("#mail_print").prop("disabled", false);
        }
    });
}

function get_po_list() {
    $.ajax({
        url: "php/get_po_list.php",
        type: "get", //send it through get method
        data: {


        },
        success: function (response) {

            console.log(response);

            if (response.trim() != "error") {
                var obj = JSON.parse(response);
                var count = 0;

                var ic = ""
                obj.forEach(function (obj) {
                    count += 1;

                    var edit = "<i class='fa-solid fa-print'  data-po_path=" + obj.po_path + "></i>"
                    ic = "<i class='fa fa-check-circle text-success pe-3'></i>"

                    if (obj.email_sent == '1') {
                        ic += "<i class='fa-solid fa-envelope-circle-check text-success'></i>";
                    }
                    // if (obj.email_sent == '0')
                    {

                        edit += "<i class='fa-solid fa-pen-to-square' data-po_id=" + obj.po_id + "></i>";
                        // ic = "<i class='fa fa-times-circle' style='color:red'></i>";
                    }
                    if (obj.approve_sts == '0') {
                        ic = "<i class='fa fa-times-circle' style='color:red'></i>";
                    }
                    $("#get_po_list").append("<tr data-po_id=" + obj.po_id + "><td>" + count + "</td><td>" + obj.po_no + "(" + obj.po_id + ")</td><td>" + obj.order_to_name + "</td><td>" + obj.po_date + "</td><td class='text-center'>" + ic + "</td><td class='text-center'>" + edit + "</td></tr>")


                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}





function check_login() {

    if (localStorage.getItem("logemail") == null && phone_id == null) {
        window.location.replace("login.html");
    }
    else if (localStorage.getItem("logemail") == null && phone_id != null) {
        get_current_userid_byphoneid();
        $('#menu_bar').hide()
    }

    else {

    }
}


function get_current_userid_byphoneid() {
    $.ajax({
        url: "php/get_current_employee_id_byphoneid.php",
        type: "get", //send it through get method
        data: {
            phone_id: phone_id,


        },
        success: function (response) {


            if (response.trim() != "error") {
                var obj = JSON.parse(response);





                obj.forEach(function (obj) {
                    current_user_id = obj.emp_id;
                    current_user_name = obj.emp_name;
                });

                //    get_sales_order()
            }

            else {
                salert("Error", "User ", "error");
            }



        },
        error: function (xhr) {
            //Do Something to handle error
        }
    });
}


function shw_toast(title, des, theme) {


    $('.toast-title').text(title);
    $('.toast-description').text(des);
    var toast = new bootstrap.Toast($('#myToast'));
    toast.show();
}

function get_millis(t) {

    var dt = new Date(t);
    return dt.getTime();
}



function get_cur_millis() {
    var dt = new Date();
    return dt.getTime();
}


function get_today_date() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();



    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T" + hour + ":" + mins;
    return today;
}

function get_today_start_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T00:00";

    return get_millis(today)

}


function get_today_end_millis() {
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;

    var today = year + "-" + month + "-" + day + "T23:59";

    return get_millis(today)

}

function salert(title, text, icon) {


    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date(millis) {
    var d = new Date(millis); // Parameter should be long value


    return d.toLocaleString('en-GB');

}