
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
  var current_user_id =  localStorage.getItem("ls_uid") ;
var current_user_name =  localStorage.getItem("ls_uname") ; 
 var physical_stock_array = [];
$(document).ready(function(){
 
  
  $("#menu_bar").load('menu.html',
    function() { 
      var lo = (window.location.pathname.split("/").pop());
      var web_addr = "#"+ (lo.substring(0, lo.indexOf(".")))
 
    
     if($(web_addr).find("a").hasClass('nav-link'))
     {
      $(web_addr).find("a").toggleClass('active')
     }
     else if($(web_addr).find("a").hasClass('dropdown-item'))
{
$(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
}
      
     
    }
 );



    check_login();
    
  $("#unamed").text(localStorage.getItem("ls_uname"))

get_jaysan_po_material()

$("#print").on("click", function(event) {
  event.preventDefault();
  // TODO: handle click here

  $.ajax({
    url: "pdf_handler.php",
    method: "POST",
    data: {
        save_path: "storage/pdf/invoice1001.pdf",
        file_name: "Invoice_1001.pdf",
        header_html: "<h3>HS Tech Soft - Invoice</h3>",
        footer_html: "<p>Generated by HS Tech Soft ERP</p>",
        body_html: `        <table class="table caption-top table-bordered table-striped ">
                    <thead>

                        <tr>
                            <th scope="col" rowspan="4" colspan="3" id="invoice_to">JAYSAN AGRI INDUSTRIAL<br>80-1, 1C, Valiyampalayam,Coimbatore - 641048<br>GSTIN/UIN : 33AALFJ3271B1ZQ<br>State Name : Tamilnadu Code : 33</th>
                            <th scope="col" colspan="2">Voucher No</th>
                            <th scope="col" colspan="3">Date</th>
                        </tr>
                        <tr>
                            <th scope="col" colspan="2"></th>
                            <th scope="col" colspan="3">Model/Terms of payment</th>
                        </tr>
                        <tr>
                            <th scope="col" colspan="2">Reference No. &amp; Date</th>
                            <th scope="col" colspan="3">Other References</th>
                        </tr>
                        <tr>
                            <th scope="col" colspan="2">Dispatched through</th>
                            <th scope="col" colspan="3">Destination</th>
                        </tr>
                        <tr>
                            <th scope="col" colspan="3" id="consignee">Consignee (Ship to) <br>Easy Tech Zone<br><br>e-mail : <br>GSTIN/UIN : 33AKYPH1911P1ZP<br>State Name : </th>
                            <th scope="col" rowspan="2" colspan="5" id="terms_of_delivery" class="text-start align-top">Terms of Delivery:<br>Transport : Extra at actuals
Payment Terms :</th>
                        </tr>
                        <tr>
                            <th scope="col" colspan="3" id="supplier">Supplier (Bill from) <br>Easy Tech Zone<br><br>GSTIN/UIN : 33AKYPH1911P1ZP<br>State Name : <br>Contact person : <br>Contact : <br>e-mail : </th>
                        </tr>
                        <tr>

                            <td>S/No</td>
                            <td>Description of Goods</td>
                            <td>Due on</td>
                            <td>Quantity</td>
                            <td>Rate</td>
                            <td>Per</td>
                            <td>Disc.%</td>
                            <td>Amount</td>

                        </tr>
                    </thead>
                    <tbody id="purchase_order_details">
                      <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                          <tr data-approve="1">
                        <td>1</td>
                        <td>001 Roller Assmbly 312</td>
                        <td>2025-10-19</td>
                        <td>0 CUM</td>
                        <td>45</td>
                        <td>CUM</td>
                        <td>0</td>
                        <td>0</td>
                      </tr>
                      <tr>
                        <th scope="col" colspan="3"></th>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td id="raw_material_total_amount_id">0</td>
                      </tr>
                      <tr>
                        <td id="gst_details" colspan="7">input cgst @6%<br>input sgst @6%<br></td>
                      
                        <td id="gst_amount_details">0.00<br>0.00<br></td>
                      </tr>
                      <tr>
                        <th scope="col"  colspan="7">Rounded Off</th>
                      
                        <td id="less">0.00</td>
                      </tr>
                      <tr>
                        <th scope="col" colspan="3">Total</th>
                       
                        <td colspan="4">0</td>
                       
                        <td id="final_total">0.00</td>
                      </tr>
                      <tr>
                        <td colspan="8">Amount Chargeable (in words)<span class="text-end">E.&amp; O.E</span><br><b> INR
                            numberToWords(Math.round(final_total));</b></td>
                      </tr>
                      <tr>
                        <td colspan="4">Remark <br>Po against by proforma</td>
                        <td colspan="4" class="text-end"><b>for JAYSAN AGRI INDUSTRIAL</b><br><br>Signature</td>
                      </tr>
                    </tbody>


                </table>

        `,
        orientation: "portrait",
        paper_size: "A4",
        stream: "no",
        // email_to: "nklharish1@gmail.com",
        // email_subject: "Invoice #1001",
        // email_body: "Hello, please find attached your invoice.",
        pdf_password: "",        // optional
        watermark_text: ""       // optional
    },
    success: function(res) {
        console.log(res);
        alert(res.message);
    },
    error: function(xhr) {
        alert("Error: " + xhr.responseText);
    }
});
});





});



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });


 function get_jaysan_po_material()
{
 

$.ajax({
  url: "php/get_jaysan_po_material.php",
  type: "get", //send it through get method
  data: {
  jaysan_po_id : 9
  },
  success: function (response) {


if (response.trim() != "error") {
console.log(response);

 if (response.trim() != "0 result")
 {

  var obj = JSON.parse(response);
var count =0 


  obj.forEach(function (obj) {
    console.log(obj.con_email);
    
   var material = JSON.parse(obj.materials_list);


 material.forEach(function (mat) {
console.log(mat.material_name);
 })
   



  });

 
}
else{
// $("#@id@") .append("<td colspan='0' scope='col'>No Data</td>");

}
}




    
  },
  error: function (xhr) {
      //Do Something to handle error
  }
});



   
}





  

   



function check_login()
{
 
if (localStorage.getItem("logemail") == null && phone_id == null )  {
 window.location.replace("login.html");
}
else if (localStorage.getItem("logemail") == null && phone_id != null )
 {
get_current_userid_byphoneid();
$('#menu_bar').hide()
 }

 else
 {
   
 }
}


function get_current_userid_byphoneid()
   {
     $.ajax({
       url: "php/get_current_employee_id_byphoneid.php",
       type: "get", //send it through get method
       data: {
         phone_id:phone_id,
        
      
      },
       success: function (response) {
      
      
      if (response.trim() != "error") {
       var obj = JSON.parse(response);
      

      console.log(response);
      
      
       obj.forEach(function (obj) {
         current_user_id = obj.emp_id;
         current_user_name =  obj.emp_name;
       });
      
    //    get_sales_order()
      }
      
      else {
       salert("Error", "User ", "error");
      }
      
      
         
       },
       error: function (xhr) {
           //Do Something to handle error
       }
      });
   }

  
   function shw_toast(title,des,theme)
   {
   
     
         $('.toast-title').text(title);
         $('.toast-description').text(des);
   var toast = new bootstrap.Toast($('#myToast'));
   toast.show();
   }  

   function get_millis(t)
   {
    
    var dt = new Date(t);
    return dt.getTime();
   }



   function get_cur_millis()
   {
    var dt = new Date();
    return dt.getTime();
   }


   function get_today_date(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();
  
console.log(mins)

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T"+ hour + ":"+ mins; 
    return today;
   }

   function get_today_start_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T00:00"; 

    return get_millis(today)
     
   }


   function get_today_end_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T23:59"; 

    return get_millis(today)
     
   }

   function salert(title, text, icon) {
  

    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date( millis)
{
  var d = new Date(millis); // Parameter should be long value

  
return d.toLocaleString('en-GB');

}