
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
  var current_user_id =  localStorage.getItem("ls_uid") ;
var current_user_name =  localStorage.getItem("ls_uname") ; 
 var physical_stock_array = [];
$(document).ready(function(){
 
  
  $("#menu_bar").load('menu.html',
    function() { 
      var lo = (window.location.pathname.split("/").pop());
      var web_addr = "#"+ (lo.substring(0, lo.indexOf(".")))
 
    
     if($(web_addr).find("a").hasClass('nav-link'))
     {
      $(web_addr).find("a").toggleClass('active')
     }
     else if($(web_addr).find("a").hasClass('dropdown-item'))
{
$(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
}
      
     
    }
 );



    check_login();
    
  $("#unamed").text(localStorage.getItem("ls_uname"))



$("#print_btn").on("click", function(event) {
  event.preventDefault();
  // TODO: handle click here

  $.ajax({
    url: "pdf_handler.php",
    method: "POST",
    data: {
        save_path: "storage/pdf/invoice1001.pdf",
        file_name: "Invoice_1001.pdf",
        header_html: "<div class='table-responsive'><table class='table table-bordered table-striped '> <thead> <tr> <th scope='col' rowspan='4' colspan='3' id='invoice_to'>JAYSAN AGRI INDUSTRIAL<br>80-1, 1C, Valiyampalayam,Coimbatore - 641048<br>GSTIN/UIN : 33AALFJ3271B1ZQ<br>State Name : Tamilnadu Code : 33</th> <th scope='col' colspan='2'>Voucher No</th> <th scope='col' colspan='3'>Date</th> </tr> <tr> <th scope='col' colspan='2'></th> <th scope='col' colspan='3'>Model/Terms of payment</th> </tr> <tr> <th scope='col' colspan='2'>Reference No. Date</th> <th scope='col' colspan='3'>Other References</th> </tr> <tr> <th scope='col' colspan='2'>Dispatched through</th> <th scope='col' colspan='3'>Destination</th> </tr> </thead></table></div>",
        footer_html: "<p>Generated by HS Tech Soft ERP</p>",
        body_html:" <div class='table-responsive'> <table class='table caption-top table-bordered table-striped ' id='purchase_order_table'> <thead> <tr> <th scope='col' colspan='3' id='consignee'>Consignee (Ship to) <br>Easy Tech Zone<br><br>e-mail : <br>GSTIN/UIN : 33AKYPH1911P1ZP<br>State Name : </th> <th scope='col' rowspan='2' colspan='5' id='terms_of_delivery'>Terms of Delivery:<br>Transport : Extra at actualsPayment Terms :</th> </tr> <tr> <th scope='col' colspan='3' id='supplier'>Supplier (Bill from) <br>Easy Tech Zone<br><br>GSTIN/UIN : 33AKYPH1911P1ZP<br>State Name : <br>Contact person : <br>Contact : <br>e-mail : </th> </tr> <tr> <td>S/No</td> <td>Description of Goods</td> <td>Due on</td> <td>Quantity</td> <td>Rate</td> <td>Per</td> <td>Disc.%</td> <td>Amount</td> </tr> </thead> <tbody id='purchase_order_details'><tr data-po_order_to='undefined' data-po_delivery_to='undefined' data-po_terms='Transport : Extra at actualsPayment Terms :' data-po_materials='[object Object],[object Object]'><td>1</td><td>001 Roller Assmbly 312</td><td>2025-10-15</td><td>12 CUM</td><td>45</td><td>CUM</td><td>0</td><td>540</td></tr><tr><th scope='col' colspan='3'></th><td></td><td></td><td></td><td></td><td id='raw_material_total_amount_id'>540</td></tr><tr><td id='gst_details'>input cgst @6%<br>input sgst @6%<br></td><td></td><td></td><td></td><td></td><td></td><td></td><td id='gst_amount_details'>32.40<br>32.40<br></td></tr><tr><th scope='col'>Rounded Off</th><td></td><td></td><td></td><td></td><td></td><td></td><td id='less'>0.20</td></tr><tr><th scope='col'>Total</th><td></td><td></td><td>12</td><td></td><td></td><td></td><td id='final_total'>605.00</td></tr></tbody> <span style='color: red; font-size: 12px; margin-left: 5px; cursor: text;'> (#purchase_order_table)</span></table> <div class='text-center'> <button type='submit' class='btn btn-primary ' id='mail_print'><i class='fa fa-envelope' aria-hidden='true'></i> / <i class='fa fa-print' aria-hidden='true'></i> </button><span style='color: red; font-size: 12px; margin-left: 5px; cursor: text;'> (#mail_print)</span> </div> </div>",
        orientation: "portrait",
        paper_size: "A4",
        stream: "yes",
        email_to: "nklharish1@gmail.com",
        email_subject: "Invoice #1001",
        email_body: "Hello, please find attached your invoice.",
        pdf_password: "",        // optional
        watermark_text: "HSTECHSOFT"       // optional
    },
    success: function(res) {
        console.log(res);
        alert(res.message);
    },
    error: function(xhr) {
        alert("Error: " + xhr.responseText);
    }
});

});


});






  function insert_material_request_form()
   {
    
   
   $.ajax({
     url: "php/insert_material_request_form.php",
     type: "get", //send it through get method
     data: {
  emp_id : emp_id,
part_id : part_id,
bom_production :  $('#bom_production :selected').val(),
order_type :  $('#order_type :selected').val(),
shortfall_qty :  $('#shortfall_qty').val(),
stock_for_sufficent_days :  $('#stock_for_sufficent_days').val(),
req_qty :  $('#req_qty').val(),
req_date :  $('#req_date').val(),
last_purchase_date :  $('#last_purchase_date').val(),
last_purchase_qty :  $('#last_purchase_qty').val(),
material_receipt_status :  $('#material_receipt_status :selected').val(),
prepared_by : emp_id,
physical_stock_array : physical_stock_array

     },
     success: function (response) {
   console.log(response);
   
   
   if (response.trim() == "ok") {

 
   
  }
   
  
   
   
       
     },
     error: function (xhr) {
         //Do Something to handle error
     }
   });
   
   
   
      
   }




  

   



function check_login()
{
 
if (localStorage.getItem("logemail") == null && phone_id == null )  {
 window.location.replace("login.html");
}
else if (localStorage.getItem("logemail") == null && phone_id != null )
 {
get_current_userid_byphoneid();
$('#menu_bar').hide()
 }

 else
 {
   
 }
}


function get_current_userid_byphoneid()
   {
     $.ajax({
       url: "php/get_current_employee_id_byphoneid.php",
       type: "get", //send it through get method
       data: {
         phone_id:phone_id,
        
      
      },
       success: function (response) {
      
      
      if (response.trim() != "error") {
       var obj = JSON.parse(response);
      

      console.log(response);
      
      
       obj.forEach(function (obj) {
         current_user_id = obj.emp_id;
         current_user_name =  obj.emp_name;
       });
      
    //    get_sales_order()
      }
      
      else {
       salert("Error", "User ", "error");
      }
      
      
         
       },
       error: function (xhr) {
           //Do Something to handle error
       }
      });
   }

  
   function shw_toast(title,des,theme)
   {
   
     
         $('.toast-title').text(title);
         $('.toast-description').text(des);
   var toast = new bootstrap.Toast($('#myToast'));
   toast.show();
   }  

   function get_millis(t)
   {
    
    var dt = new Date(t);
    return dt.getTime();
   }



   function get_cur_millis()
   {
    var dt = new Date();
    return dt.getTime();
   }


   function get_today_date(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    var hour = date.getHours();
    var mins = date.getMinutes();
  
console.log(mins)

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T"+ hour + ":"+ mins; 
    return today;
   }

   function get_today_start_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T00:00"; 

    return get_millis(today)
     
   }


   function get_today_end_millis(){
    var date = new Date();

    var day = date.getDate();
    var month = date.getMonth() + 1;
    var year = date.getFullYear();

    if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
 
    var today = year + "-" + month + "-" + day +"T23:59"; 

    return get_millis(today)
     
   }

   function salert(title, text, icon) {
  

    swal({
        title: title,
        text: text,
        icon: icon,
    });
}



function millis_to_date( millis)
{
  var d = new Date(millis); // Parameter should be long value

  
return d.toLocaleString('en-GB');

}