
var urlParams = new URLSearchParams(window.location.search);
var phone_id = urlParams.get('phone_id');
var current_user_id = localStorage.getItem("ls_uid");
var current_user_name = localStorage.getItem("ls_uname");
var physical_stock_array = [];
$(document).ready(function () {


  $("#menu_bar").load('menu.html',
    function () {
      var lo = (window.location.pathname.split("/").pop());
      var web_addr = "#" + (lo.substring(0, lo.indexOf(".")))


      if ($(web_addr).find("a").hasClass('nav-link')) {
        $(web_addr).find("a").toggleClass('active')
      }
      else if ($(web_addr).find("a").hasClass('dropdown-item')) {
        $(web_addr).parent().parent().find("a").eq(0).toggleClass('active')
      }


    }
  );



  check_login();

  $("#unamed").text(localStorage.getItem("ls_uname"))


  $("#printInvoice").on("click", function (event) {
    event.preventDefault();
    // TODO: handle click here

    const win = window.open("storage%2Fpdf%2Finvoice1001.pdf", "_blank");
    // Some browsers need a delay before printing
    const printTimer = setInterval(() => {
      if (win.document.readyState === "complete") {
        clearInterval(printTimer);
        win.focus();
        win.print();
      }
    }, 500);
  });
  $("#print").on("click", function (event) {
    event.preventDefault();
    // TODO: handle click here
    var invoiceHtml = $("#invoicePreview").prop("outerHTML");

    // Encode it to protect HTML structure in POST
    var encodedHtml = encodeURIComponent(invoiceHtml);
    $.ajax({
      url: "pdf_handler.php",
      method: "POST",
      data: {
        save_path: "storage/pdf/invoice1001",
        file_name: "Invoice.pdf",
        unique_file: "no",
        header_html: "<h3>HS Tech Soft - Invoice</h3>",
        footer_html: "<p>Generated by HS Tech Soft ERP</p>",
        body_html: encodedHtml,
        orientation: "portrait",
        paper_size: "A4",
        stream: "no",
        // email_to: "nklharish1@gmail.com",
        // email_subject: "Invoice #1001",
        // email_body: "Hello, please find attached your invoice.",
        // pdf_password: "",        // optional
        // watermark_text: ""       // optional
      },
      success: function (res) {
        console.log(res);
        if (res.download_url) {
          // 3️⃣ open PDF and trigger browser print dialog
          const win = window.open(res.download_url, "_blank");
          // Some browsers need a delay before printing
          const printTimer = setInterval(() => {
            if (win.document.readyState === "complete") {
              clearInterval(printTimer);
              win.focus();
              win.print();
            }
          }, 500);
        } else {
          alert("PDF generated, but no download URL returned");
        }
      },
      error: function (xhr) {
        alert("Error: " + xhr.responseText);
      }
    });
  });

  get_all_bom()

  $("#excle_btn").click(function () {

    let table = document.querySelector("table");
    let html = table.outerHTML;

    let url = 'data:application/vnd.ms-excel,' + encodeURIComponent(html);

    let link = document.createElement("a");
    link.href = url;
    link.download = "BOM_Report.xls";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

  });

});



// $.ajax({
//     url: "pdf_handler.php",
//     method: "POST",
//     data: {
//         save_path: "E:/web/htdocs/jaysanERP/storage/pdf/invoice1001.pdf",
//         file_name: "Invoice_1001.pdf",
//         header_html: "<h3>HS Tech Soft - Invoice</h3>",
//         footer_html: "<p>Generated by HS Tech Soft ERP</p>",
//         body_html: `
//             <h2>Invoice #1001</h2>
//             <p><strong>Customer:</strong> Jaysan Agri Industrial</p>
//             <table>
//               <thead>
//                 <tr><th>Sl.No</th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>
//               </thead>
//               <tbody>
//                 <tr><td>1</td><td>Baler Service</td><td>1</td><td>1500</td><td>1500</td></tr>
//                 <tr><td>2</td><td>Spare Part</td><td>2</td><td>450</td><td>900</td></tr>
//               </tbody>
//               <tfoot>
//                 <tr><td colspan="4" style="text-align:right">Grand Total</td><td>2400</td></tr>
//               </tfoot>
//             </table>
//         `,
//         orientation: "portrait",
//         paper_size: "A4",
//         stream: "no",
//         email_to: "nklharish1@gmail.com",
//         email_subject: "Invoice #1001",
//         email_body: "Hello, please find attached your invoice.",
//         pdf_password: "",        // optional
//         watermark_text: ""       // optional
//     },
//     success: function(res) {
//         console.log(res);
//         alert(res.message);
//     },
//     error: function(xhr) {
//         alert("Error: " + xhr.responseText);
//     }
// });

function get_all_bom() {

  $.ajax({
    url: "php/get_all_bom.php",
    type: "get",
    data: {
      part_id: 4074,
      component_cat: "312 4G S",
    },
    success: function (response) {

      let data = JSON.parse(response);
      $("#all_bom_table").empty();

      data.forEach((item, index) => {

        $("#all_bom_table").append(`
          <tr>
            <td>${index + 1}</td>
            <td>${item.parent_bom_id}</td>
            <td>${item.component_cat}</td>
            <td>${item.output_part_id}</td>
            <td>${item.output_part_name}</td>
            <td>${item.input_part_id}</td>
            <td>${item.input_part_name}</td>
            <td>${item.qty}</td>
            <td>${item.sub_ass_qty}</td>
            <td>${item.bomlist_id}</td>
            <td>${item.level}</td>
            <td>${item.path}</td>
            <td>${item.time_taken ?? ""}</td>
            <td>${item.category ?? ""}</td>
            <td>${item.creditor_name ?? ""}</td>
          </tr>
        `);

      });

    },
    error: function (xhr) {
      console.log(xhr);
    }
  });

}






function insert_new_process(processId) {

  $.ajax({
    url: "php/insert_nprocess.php",
    type: "get", //send it through get method
    data: {

      process_id: processId,
      edit_process_id: edit_process_id,
      input_part_id: sel_input_part_id,
      output_part_id: sel_output_part_id,
    },
    success: function (response) {
      console.log(response);



      if (response.trim()) {
        sessionStorage.setItem('editProcessId', response.trim());
        sessionStorage.setItem('breadcrumb', $('#out_breadcrumb').html());
        // Reload the page
        location.reload();
      }





    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });




}













function check_login() {

  if (localStorage.getItem("logemail") == null && phone_id == null) {
    window.location.replace("login.html");
  }
  else if (localStorage.getItem("logemail") == null && phone_id != null) {
    get_current_userid_byphoneid();
    $('#menu_bar').hide()
  }

  else {

  }
}


function get_current_userid_byphoneid() {
  $.ajax({
    url: "php/get_current_employee_id_byphoneid.php",
    type: "get", //send it through get method
    data: {
      phone_id: phone_id,


    },
    success: function (response) {


      if (response.trim() != "error") {
        var obj = JSON.parse(response);


        console.log(response);


        obj.forEach(function (obj) {
          current_user_id = obj.emp_id;
          current_user_name = obj.emp_name;
        });

        //    get_sales_order()
      }

      else {
        salert("Error", "User ", "error");
      }



    },
    error: function (xhr) {
      //Do Something to handle error
    }
  });
}


function shw_toast(title, des, theme) {


  $('.toast-title').text(title);
  $('.toast-description').text(des);
  var toast = new bootstrap.Toast($('#myToast'));
  toast.show();
}

function get_millis(t) {

  var dt = new Date(t);
  return dt.getTime();
}



function get_cur_millis() {
  var dt = new Date();
  return dt.getTime();
}


function get_today_date() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  var hour = date.getHours();
  var mins = date.getMinutes();

  console.log(mins)

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T" + hour + ":" + mins;
  return today;
}

function get_today_start_millis() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T00:00";

  return get_millis(today)

}


function get_today_end_millis() {
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day + "T23:59";

  return get_millis(today)

}

function salert(title, text, icon) {


  swal({
    title: title,
    text: text,
    icon: icon,
  });
}



function millis_to_date(millis) {
  var d = new Date(millis); // Parameter should be long value


  return d.toLocaleString('en-GB');

}